[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "SAFE Authenticator"
homepage = "http://maidsafe.net"
license = "GPL-3.0"
name = "safe_authenticator"
readme = "README.md"
repository = "https://github.com/maidsafe/safe_client_libs"
version = "0.22.0"

[dependencies]
clippy = { version = "=0.0.99", optional = true }
ffi_utils = { path = "../ffi_utils" }
futures = "~0.1.6"
lazy_static = "~0.2.1"
log = "~0.3.6"
maidsafe_utilities = "~0.10.0"
# routing = "~0.27.1"
routing = { git = "https://github.com/madadam/routing.git", branch = "mutable-data" }
rust_sodium = "~0.1.2"
rustc-serialize = "~0.3.22"
safe_core = { path = "../safe_core" }
tokio-core = "~0.1.1"
unwrap = "~1.1.0"

[features]
use-mock-routing = ["safe_core/use-mock-routing"]

[lib]
crate_type = ["staticlib", "rlib", "cdylib"]
