[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "SAFE Authenticator"
documentation = "https://docs.rs/safe_authenticator"
homepage = "https://maidsafe.net"
license = "GPL-3.0"
name = "safe_authenticator"
readme = "README.md"
repository = "https://github.com/maidsafe/safe_client_libs"
version = "0.8.0"
build = "build.rs"

[dependencies]
config_file_handler = "~0.11.0"
ffi_utils = "~0.10.0"
futures = "~0.1.17"
log = "~0.4.1"
lru-cache = "~0.1.1"
maidsafe_utilities = "~0.16.0"
rand = "~0.3.18"
routing = "~0.37.0"
rust_sodium = "~0.10.0"
safe_core = { path = "../safe_core", version = "~0.31.0" }
serde = "~1.0.27"
serde_derive = "~1.0.27"
tiny-keccak = "~1.3.1"
tokio-core = "~0.1.12"
unwrap = "~1.2.0"
jni = { version = "~0.10.2", optional = true }

[dev-dependencies.safe_core]
path = "../safe_core"
version = "~0.31.0"
features = ["testing"]

[build-dependencies]
ffi_utils = "~0.10.0"
jni = "~0.10.1"
routing = "~0.37.0"
rust_sodium = "~0.10.0"
safe_bindgen = "~0.10.0"
unwrap = "~1.2.0"

[features]
use-mock-routing = ["testing", "safe_core/use-mock-routing"]
testing = ["safe_core/testing"]
bindings = []

[lib]
crate_type = ["staticlib", "rlib", "cdylib"]
