os:
  - linux
  - osx
language: rust
rust: 
    - 1.0.0-beta
    - nightly
sudo: true
env:
  global:
    secure: "Q8EsABb7DUUkuhefjncpuIKv1P49woHligAlnT2acSj7NZIxKwovgZzKwk13IEHf/CvqWq9lFX8CS6hHE2WJjmgG35EJ8ctFulBo72WRhhDEZy2kdgCnuMoQsjnFE5dT7ZhB/8qP5iZU9p0W0YqcaVwFyEnTeu/9R598klgaXYg="

install:
- wget https://github.com/jedisct1/libsodium/releases/download/1.0.0/libsodium-1.0.0.tar.gz
- tar xvfz libsodium-1.0.0.tar.gz
- cd libsodium-1.0.0 && ./configure --prefix=/usr && make && sudo make install && cd ..
script:
    - cargo build --verbose
    - cargo test --verbose
after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  cargo doc &&
  echo "<meta http-equiv=refresh content=0;url=`echo $TRAVIS_REPO_SLUG | cut -d '/' -f 2`/index.html>" > target/doc/index.html &&
  sudo pip install ghp-import &&
  ghp-import -n target/doc &&
  git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages;
  sudo apt-get install libcurl4-openssl-dev libelf-dev libdw-dev &&
  wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
  tar xzf master.tar.gz &&
  mkdir kcov-master/build &&
  cd kcov-master/build &&
  cmake .. &&
  make &&
  sudo make install &&
  cd ../.. &&
  kcov --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo target/kcov target/debug/maidsafe_types-*;
