vars:
  - &stable "1.26.2"
  - &stable-i686 "1.26.2-i686-unknown-linux-gnu"
  - &nightly "nightly-2018-06-10"
env:
  global:
    - RUST_BACKTRACE=1
    - RUSTFLAGS="-C opt-level=2 -C codegen-units=8"
    - PATH=$PATH:$HOME/.cargo/bin
    - RUST_STABLE=1.26.2
    - RUST_NIGHTLY=nightly-2018-06-10
    - RUST_RUSTFMT=0.8.2
    - RUST_CLIPPY=0.0.207
language: rust
stages:
  - warmup-real
  - warmup-mock
  - tests-stable
  - tests-nightly
jobs:
  include:
    # Warm up the cache for a real build
    - stage: warmup-real
      script: set -x; scripts/build-ffi-utils && scripts/build-real
      os: linux
      rust: *stable
    - stage: warmup-real
      script: set -x; scripts/build-ffi-utils && scripts/build-real
      if: type = push
      os: linux
      rust: *stable-i686
      addons:
        apt:
          packages:
            - gcc-multilib
    - stage: warmup-real
      script: set -x; scripts/build-ffi-utils && scripts/build-real
      if: type = pull_request
      os: linux
      rust: *nightly
      
    # Warm up the cache for a mock build
    - stage: warmup-mock
      script: set -x; scripts/build-mock
      os: linux
      rust: *stable
    - stage: warmup-mock
      script: set -x; scripts/build-mock
      if: type = push
      os: linux
      rust: *stable-i686
      addons:
        apt:
          packages:
            - gcc-multilib
    - stage: warmup-mock
      script: set -x; scripts/build-mock
      if: type = pull_request
      os: linux
      rust: *nightly
      
    # Stable + nightly clippy
    - stage: tests-stable
      script: set -x; scripts/stable && scripts/test-binary
      os: linux
      rust: *stable
    - stage: tests-stable
      script: set -x; scripts/stable
      os: osx
      rust: *stable
    - stage: tests-stable
      script: set -x; scripts/stable
      if: type = push
      os: linux
      rust: *stable-i686
      addons:
        apt:
          packages:
            - gcc-multilib
    - stage: tests-stable
      script: set -x; scripts/rustfmt && scripts/clippy-all
      if: type = pull_request
      os: linux
      rust: *nightly
      env: RUN_RUSTFMT=1
      
    # Nightly tests
    - stage: tests-nightly
      script: set -x; scripts/test-all
      if: type = pull_request
      os: linux
      rust: *nightly
    - stage: tests-nightly
      script: set -x; scripts/build-binary
      if: type = push
      os: linux
      rust: *stable
sudo: false
cache:
  # Double the default timeout.
  timeout: 360
  cargo: true
  directories:
    - "${HOME}/.cache/master"
before_script:
  # Expected version change PR title format:
  # Version change: safe_app to 0.2.2; safe_authenticator to 0.2.3; safe_core to 0.26.0;
  - if [[ "$TRAVIS_COMMIT_MESSAGE" =~ [Vv]ersion[[:space:]]change.*safe_authenticator[[:space:]]to[[:space:]]([^;]+) ]]; then
      SAFE_AUTHENTICATOR_VERSION=v$(cargo pkgid --manifest-path=safe_authenticator/Cargo.toml | sed -e "s/.*[:#]\(.*\)/\1/");
      if [[ "v${BASH_REMATCH[1]}" != $SAFE_AUTHENTICATOR_VERSION ]]; then
        echo "Version mismatch between commit message and Cargo.toml for safe_authenticator.";
        false;
      fi;
    else
      SAFE_AUTHENTICATOR_VERSION=${TRAVIS_COMMIT:0:7};
    fi
  - if [[ "$TRAVIS_COMMIT_MESSAGE" =~ [Vv]ersion[[:space:]]change.*safe_app[[:space:]]to[[:space:]]([^;]+) ]]; then
      SAFE_APP_VERSION=v$(cargo pkgid --manifest-path=safe_app/Cargo.toml | sed -e "s/.*[:#]\(.*\)/\1/");
      if [[ "v${BASH_REMATCH[1]}" != $SAFE_APP_VERSION ]]; then
        echo "Version mismatch between commit message and Cargo.toml for safe_app.";
        false;
      fi;
    else
      SAFE_APP_VERSION=${TRAVIS_COMMIT:0:7};
    fi
  - curl -sSL https://github.com/maidsafe/QA/raw/master/travis/cargo_install.sh > cargo_install.sh
  - bash cargo_install.sh cargo-prune;
  - if [ "$TRAVIS_RUST_VERSION" = "$RUST_NIGHTLY" ] && [ "$RUN_RUSTFMT" ]; then
      bash cargo_install.sh rustfmt-nightly "$RUST_RUSTFMT";
      bash cargo_install.sh clippy "$RUST_CLIPPY";
    fi
after_script:
  - if [[ $TRAVIS_EVENT_TYPE = pull_request && -n $(git diff --shortstat 2> /dev/null | tail -n1) ]]; then
      echo "Working tree is dirty after building.  Probably Cargo.lock should be updated.";
      git status;
      travis_terminate 1;
    fi
before_cache:
  - cargo prune
before_deploy:
  - bash cargo_install.sh cargo-script 0.2.8
  - mkdir -p target/deploy
  # Build for mock.
  - ./scripts/package.rs --lib --name safe_app -d target/deploy --mock
  - ./scripts/package.rs --lib --name safe_authenticator -d target/deploy --mock
  # Build for production.
  - ./scripts/package.rs --lib --name safe_app -d target/deploy
  - ./scripts/package.rs --lib --name safe_authenticator -d target/deploy
deploy:
  provider: s3
  access_key_id: AKIAIA2TXTG7EV5VIG2Q
  secret_access_key:
    secure: qEDay6TCAy3tBLqLYFOx9OjAdoRl010paK2//teFETfwUfJA/RtNSfkp1yrgx+kZ3FO8cthdDnwR3zjM3pkCL+5mGkQMAgvRY7rcEB5H1VyO4jkZRoB4n/yUu5jB4dHdeeRWTOJxNOOPA0G1Q65LLkJql2JGoJatqE3pBmJm0X8=
  bucket: safe-client-libs
  local-dir: target/deploy
  acl: public_read
  region: eu-west-2
  skip_cleanup: true
  on:
    branch: master
    tags: false
    condition: $TRAVIS_RUST_VERSION =~ $RUST_STABLE && $TRAVIS_EVENT_TYPE = push
after_deploy: rm -rf target/deploy
