env:
  global:
    - RUST_BACKTRACE=1
    - PATH=$PATH:$HOME/.cargo/bin
language: rust
rust: stable
branches:
  only:
    - master
cache:
  cargo: true
before_script:
  - curl -sSL https://github.com/maidsafe/QA/raw/master/travis/cargo_install.sh > cargo_install.sh
  - bash cargo_install.sh cargo-prune;
  - rustup component add rustfmt clippy
jobs:
  include:
    - script: scripts/clippy --verbose
      env: CACHE_NAME=clippy_linux
      os: linux
    - script: scripts/tests --verbose
      env: CACHE_NAME=tests_linux
      os: linux
    - script: scripts/tests --verbose
      env: CACHE_NAME=tests_osx
      os: osx
before_cache:
  - cargo prune
