env:
  global:
    - Features=use-mock-routing
    - RUST_BACKTRACE=1
    - PATH=$PATH:$HOME/.cargo/bin
os:
  - linux
  - osx
language: rust
rust:
  - stable
  - nightly
sudo: false
branches:
  only:
    - master
    - dev
cache:
  cargo: true
before_script:
  - (which cargo-install-update && cargo install-update cargo-update) || cargo install cargo-update
  - (which rustfmt && cargo install-update rustfmt) || cargo install rustfmt
  - (which cargo-prune && cargo install-update cargo-prune) || cargo install cargo-prune
script:
  - if [ "${TRAVIS_RUST_VERSION}" = stable ]; then
      (
        set -x;
        cd ffi_utils &&
        cargo fmt -- --write-mode=diff &&
        cargo test  --verbose --release
      );
    fi
  - if [ "${TRAVIS_RUST_VERSION}" = stable ]; then
      (
        set -x;
        cd safe_core &&
        cargo fmt -- --write-mode=diff &&
        cargo rustc --verbose --release -- --test -Zno-trans &&
        cargo test  --verbose --release --features use-mock-routing
      );
    fi
  - if [ "${TRAVIS_RUST_VERSION}" = stable ]; then
      (
        set -x;
        cd safe_app &&
        cargo fmt -- --write-mode=diff &&
        cargo rustc --verbose --release -- --test -Zno-trans &&
        cargo test  --verbose --release --features use-mock-routing
      );
    fi
  - if [ "${TRAVIS_RUST_VERSION}" = stable ]; then
      (
        set -x;
        cd safe_authenticator &&
        cargo fmt -- --write-mode=diff &&
        cargo rustc --verbose --release -- --test -Zno-trans &&
        cargo test  --verbose --release --features use-mock-routing
      );
    fi
  - curl -sSL https://github.com/maidsafe/QA/raw/master/bash_scripts/travis/run_clippy.sh | bash
before_cache:
  - cargo prune
