environment:
  global:
    RUST_BACKTRACE: 1
  matrix:
    - RUST_TOOLCHAIN: 1.28.0

cache:
  - '%USERPROFILE%\.cargo'
  - '%APPVEYOR_BUILD_FOLDER%\target'

clone_depth: 1

install:
  - ps: |
        $url = "https://github.com/maidsafe/QA/raw/master/appveyor/install_rustup.ps1"
        Invoke-WebRequest $url -OutFile "install_rustup.ps1"
        . ".\install_rustup.ps1"

platform:
  - x86
  - x64

configuration:
  - Release

skip_tags: true

before_build:
  - ps: |
        $COMMIT_MESSAGE = "$env:APPVEYOR_REPO_COMMIT_MESSAGE $env:APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED"
        if ($COMMIT_MESSAGE -match "[Vv]ersion change.*safe_authenticator to ([^;]+)") {
          $COMMIT_MESSAGE_VERSION = "v" + $Matches[1]
          $env:SAFE_AUTHENTICATOR_VERSION = (cargo pkgid --manifest-path=safe_authenticator/Cargo.toml) -Replace '.*[:#](.*)', 'v$1'
          if ($COMMIT_MESSAGE_VERSION -ne $env:SAFE_AUTHENTICATOR_VERSION) {
            Write-Error "Version mismatch between commit message and Cargo.toml for safe_authenticator."
            exit 1
          }
        } else {
          $env:SAFE_AUTHENTICATOR_VERSION = $env:APPVEYOR_REPO_COMMIT.Substring(0,7)
        }
        if ($COMMIT_MESSAGE -match "[Vv]ersion change.*safe_app to ([^;]+)") {
          $COMMIT_MESSAGE_VERSION = "v" + $Matches[1]
          $env:SAFE_APP_VERSION = (cargo pkgid --manifest-path=safe_app/Cargo.toml) -Replace '.*[:#](.*)', 'v$1'
          if ($COMMIT_MESSAGE_VERSION -ne $env:SAFE_APP_VERSION) {
            Write-Error "Version mismatch between commit message and Cargo.toml for safe_app."
            exit 1
          }
        } else {
          $env:SAFE_APP_VERSION = $env:APPVEYOR_REPO_COMMIT.Substring(0,7)
        }

build_script:
  - |-
    cargo check --verbose --release --lib --tests --manifest-path=ffi_utils/Cargo.toml
    cargo check --verbose --release --features testing --lib --tests --manifest-path=safe_core/Cargo.toml
    cargo check --verbose --release --features testing --lib --tests --manifest-path=safe_authenticator/Cargo.toml
    cargo check --verbose --release --features testing --lib --tests --manifest-path=safe_app/Cargo.toml
    cargo check --verbose --release --lib --tests --manifest-path=tests/Cargo.toml

after_build:
  - ps: |
        if (git diff --shortstat) {
          Write-Error "Working tree is dirty after building.  Probably Cargo.lock should be updated."
          git status
          exit 1
        }

test_script:
  - |-
    cargo test --verbose --release --manifest-path=ffi_utils/Cargo.toml
    cargo test --verbose --release --features=use-mock-routing --manifest-path=safe_core/Cargo.toml
    cargo test --verbose --release --features=use-mock-routing --manifest-path=safe_authenticator/Cargo.toml
    cargo test --verbose --release --features=use-mock-routing --manifest-path=safe_app/Cargo.toml

before_deploy:
  - ps: |
        $url = "https://s3.eu-west-2.amazonaws.com/download-native-libs/cargo-script.exe"
        Invoke-WebRequest $url -OutFile "cargo-script.exe"
        New-Item -Path ".\target\deploy" -ItemType directory
  - cargo-script.exe script -- ./scripts/package.rs --lib --name safe_app -d target/deploy --mock
  - cargo-script.exe script -- ./scripts/package.rs --lib --name safe_authenticator -d target/deploy --mock
  - cargo-script.exe script -- ./scripts/package.rs --lib --name safe_app -d target/deploy
  - cargo-script.exe script -- ./scripts/package.rs --lib --name safe_authenticator -d target/deploy
  - ps: $root = Resolve-Path .\target\deploy; [IO.Directory]::GetFiles($root.Path, '*.zip') | % { Push-AppveyorArtifact $_ -FileName $_.Substring($root.Path.Length + 1) }

deploy:
  provider: S3
  access_key_id: AKIAIA2TXTG7EV5VIG2Q
  secret_access_key:
    secure: WtcjRuYVPF9Fhv1qBVBG+rP6VR7HEa+IayW1L8GqhgUJmp1M8gV4J9u/TdY5Fsb2
  bucket: safe-client-libs
  region: eu-west-2
  set_public: true
  artifact: /.*\.zip/
  on:
    branch: master
