environment:
  global:
    GH_TOKEN:
      secure: Plf6CbvLc5BWpB51EU9Sk/RMow47fZp74uSKt1Wv20kFRf1OQS2pVuEzgXQPuyhW
    RUST_BACKTRACE: 1
  matrix:
    - RUST_TOOLCHAIN: stable

clone_depth: 1

skip_tags: true

cache:
  - '%USERPROFILE%\.cargo'
  - '%APPVEYOR_BUILD_FOLDER%\target'

install:
  - ps: |
        $url = "https://github.com/maidsafe/QA/raw/master/appveyor/install_rustup.ps1"
        Invoke-WebRequest $url -OutFile "install_rustup.ps1"
        . ".\install_rustup.ps1"

platform:
  - x86
  - x64

configuration:
  - Release

build_script:
  - cargo check --verbose --release --all-targets

after_build:
  - ps: |
        if (git diff --shortstat) {
          Write-Error "Working tree is dirty after building.  Probably Cargo.lock should be updated."
          git status
          exit 1
        }

test_script:
  - cargo test --verbose --release
