environment:
  global:
    GH_TOKEN:
      secure: Plf6CbvLc5BWpB51EU9Sk/RMow47fZp74uSKt1Wv20kFRf1OQS2pVuEzgXQPuyhW
    PROJECT_NAME: safe_vault
    RUST_BACKTRACE: 1
  matrix:
    - RUST_TOOLCHAIN: 1.24.0

clone_depth: 1

skip_tags: true

cache:
  - '%USERPROFILE%\.cargo'
  - '%APPVEYOR_BUILD_FOLDER%\target'

install:
  - ps: |
        $url = "https://github.com/maidsafe/QA/raw/master/appveyor/install_rustup.ps1"
        Invoke-WebRequest $url -OutFile "install_rustup.ps1"
        . ".\install_rustup.ps1"

        $commit_message = "$env:APPVEYOR_REPO_COMMIT_MESSAGE $env:APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED"

        if ($commit_message -match "[vV]ersion change to v?(.*)") {
          $env:PROJECT_VERSION = $matches[1]
          $env:DEPLOY = "true"
        }

platform:
  - x86
  - x64

configuration:
  - Release

build_script:
  - cargo check --verbose --lib --tests
  - cargo check --verbose --features use-mock-routing --lib --tests
  - cargo check --verbose --features use-mock-crust --lib --tests

after_build:
  - ps: |
        if (git diff --shortstat) {
          Write-Error "Working tree is dirty after building.  Probably Cargo.lock should be updated."
          git status
          exit 1
        }

test_script:
  - cargo test --verbose --release --features use-mock-routing
  - cargo test --verbose --release --features use-mock-crust

before_deploy:
  - ps: . ".\ci\appveyor\before_deploy.ps1"

deploy:
  provider: GitHub
  auth_token: $(GH_TOKEN)
  # Deploy the archive (zip) and the installer (exe)
  artifact: /.*\.zip|.*\.exe/
  draft: true
  tag: $(PROJECT_VERSION)
  on:
    DEPLOY: true
    RUST_VERSION: stable
