[package]
name = "sn_cli"
version = "0.36.0"
description = "Safe CLI"
authors = [
  "bochaco <gabrielviganotti@gmail.com>",
  "Josh Wilson <joshuef@gmail.com>"
]
publish = false
license = "MIT OR BSD-3-Clause"
default-run = "safe"
repository = "https://github.com/maidsafe/sn_cli"
edition = "2018"

[[bin]]
name = "safe"
path = "src/main.rs"

[dependencies]
ansi_term = "~0.12"
async-std = "1.9.0"
chrono = "~0.4"
color-eyre = "~0.5"
console = "~0.14"
dirs-next = "2.0.0"
hex = "~0.4"
human-panic = "1.0.3"
isatty = "~0.1"
num-traits = "~0.2"
percent-encoding = "2.1.0"
pretty-hex = "~0.2"
prettytable-rs = "~0.8"
rand = "~0.7"
relative-path = "1.3.2"
sn_launch_tool = "~0.7.0"
serde = "1.0.123"
serde_json = "1.0.62"
serde_yaml = "~0.8"
shrust = "~0.0.7"
structopt = "~0.3"
tracing = "~0.1.26"
tracing-appender = "~0.1.2"
tracing-subscriber = "~0.2.15"
url = "2.2.2"
xor_name = "3.0.0"

  [dependencies.bls]
  package = "blsttc"
  version = "2.0.1"

  [dependencies.bytes]
  version = "1.0.1"
  features = [ "serde" ]

  [dependencies.ed25519-dalek]
  version = "1.0.1"
  features = [ "serde" ]

  [dependencies.indicatif]
  git = "https://github.com/mibac138/indicatif"
  branch = "mpb-tick"

  [dependencies.reqwest]
  version = "~0.11"
  default-features = false
  features = [ "rustls-tls" ]
  optional = true

  [dependencies.sn_api]
  version = "~0.37"
  default-features = false
  features = [ "app", "authd_client", "testing" ]

  [dependencies.tokio]
  version = "1.6.0"
  features = [ "macros" ]

  [dependencies.self_update]
  git = "https://github.com/jacderida/self_update.git"
  branch = "github_download_json_parsing"
  default-features = false
  features = [
  "rustls",
  "archive-tar",
  "archive-zip",
  "compression-flate2",
  "compression-zip-deflate"
]
  optional = true

[features]
default = [ "testing", "self-update" ]
testing = [ "sn_api/testing" ]
self-update = [ "reqwest", "self_update" ]

[dev-dependencies]
assert_cmd = "~2.0"
assert_fs = "~1.0"
ctor = "~0.1"
duct = "~0.12"
predicates = "~2.0"
criterion = "~0.3"
walkdir = "2.3.1"
multibase = "~0.6"
xor_name = "2.0.0"

  [dev-dependencies.sn_cmd_test_utilities]
  path = "./sn_cmd_test_utilities"

[[bench]]
name = "put"
harness = false

[[bench]]
name = "keys"
harness = false
