[package]
name = "safe_cli"
version = "0.0.1"
description = "SAFE CLI"
authors = ["bochaco <gabrielviganotti@gmail.com>", "Josh Wilson <joshuef@gmail.com>"]
publish = false
edition = "2018"
license = "GPL-3.0"

[dependencies]
log = "0.4.6"
#safe_app = "0.9.1"
rpassword = "3.0.1"
structopt = "0.2.14"
env_logger = "0.6.0"
rand = "0.6.5"
prettytable-rs = "^0.8"
unwrap = "~1.2.0"
threshold_crypto = "0.3.1"
uuid = "0.7"

[features]
default = ["uuid/v4"]
#mock-network = ["safe_app/mock-network"]

[patch.crates-io]
#safe_app = { git = "https://github.com/bochaco/safe_client_libs", branch = "safe_authenticator-master-upgrades" }

[dev-dependencies]
pretty_assertions = "0.6.1"

[dev-dependencies.cargo-husky]
version = "1"
default-features = false # Disable features which are enabled by default
features = ["precommit-hook","user-hooks"]
