[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "SAFE Core API library"
documentation = "http://maidsafe.github.io/safe_core/latest/"
homepage = "http://maidsafe.net"
license = "GPL-3.0"
name = "safe_core"
readme = "README.md"
repository = "https://github.com/maidsafe/safe_core"
version = "0.5.0"

[dependencies]
clippy = {version = "~0.0.37", optional = true}
log = "~0.3.4"
lru_time_cache = "~0.2.5"
maidsafe_utilities = "~0.2.0"
rand = "~0.3.12"
routing = "~0.7.0"
rustc-serialize = "~0.3.16"
self_encryption = "~0.2.5"
sodiumoxide = "~0.0.9"
xor_name = "~0.0.3"
mpid_messaging = "~0.1.0"

[features]
use-mock-routing = []
