[package]
name = "sn_api"
version = "0.33.0"
description = "Safe API"
authors = [
  "bochaco <gabrielviganotti@gmail.com>",
  "Josh Wilson <joshuef@gmail.com>"
]
license = "MIT OR BSD-3-Clause"
repository = "https://github.com/maidsafe/sn_api"
include = [ "Cargo.toml", "src/*" ]
edition = "2018"

[dependencies]
async-trait = "~0.1"
bincode = "1.3.1"
chrono = "~0.4"
dirs-next = "2.0.0"
env_logger = "~0.8"
futures = "~0.3"
hex = "~0.4"
hmac = "~0.10"
lazy_static = "1.4.0"
log = "~0.4"
mime_guess = "2.0.3"
multibase = "~0.9"
qjsonrpc = "~0.2"
rand = "~0.7"
rand_core = "~0.5"
relative-path = "1.3.2"
rmp-serde = "~0.15"
serde = "1.0.123"
serde_json = "1.0.62"
sha3 = "~0.9"
# safe_network = "0.10.0"
safe_network = {path = "../safe_network"}
thiserror = "1.0.23"
uhttp_uri = "~0.5"
url = "2.2.0"
urlencoding = "1.1.1"
walkdir = "2.3.1"
xor_name = "1"

  [dependencies.ed25519-dalek]
  version = "1.0.1"
  features = [ "serde" ]

  [dependencies.pbkdf2]
  version = "~0.7"
  default-features = false

  [dependencies.tokio]
  version = "1.6.0"
  features = [ "rt" ]

  [dependencies.tiny-keccak]
  version = "2.0.2"
  features = [ "sha3" ]

[features]
authenticator = [ ]
authd_client = [ ]
app = [ ]
testing = [ "safe_network/testing" ]
default = [ "testing", "authenticator", "authd_client", "app" ]

[dev-dependencies]
anyhow = "1.0.38"
proptest = "~0.10"
tracing-subscriber = "~0.2"

  [dev-dependencies.tokio]
  version = "1.6.0"
  features = [ "macros" ]
