[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Implementation of the 'Vault' node for the SAFE Network."
documentation = "https://docs.rs/safe_vault"
edition = "2018"
homepage = "https://maidsafe.net"
license = "GPL-3.0"
name = "safe_vault"
readme = "README.md"
repository = "https://github.com/maidsafe/safe_vault"
version = "0.24.0"

[patch.crates-io]
safe-nd = { git = "https://github.com/maidsafe/safe-nd.git", branch = "master" }
safe-transfers = { git = "https://github.com/maidsafe/safe-transfers.git" }
self_encryption = { git = "https://github.com/joshuef/self_encryption.git", branch = "AllowMutGet" }

[dependencies]
base64 = "~0.10.1"
# Ensure bincode version is identical to that in SAFE Client Libs and SAFE Network Data.
bincode = "1.2.1"
bytes = { version = "~0.5.4", features = ["serde"] }
crossbeam-channel = "~0.4.2"
ctrlc = "3.1.3"
directories = "2.0.1"
fake_clock = "~0.3.0"
flexi_logger = "~0.14.8"
fxhash = { version = "~0.2.1", optional = true }
hex = "~0.3.2"
hex_fmt = "~0.3.0"
lazy_static = "1"
log = "~0.4.7"
mock-quic-p2p = { git = "https://github.com/maidsafe/quic-p2p", branch = "igd-err", optional = true }
pickledb = "~0.4.0"
quick-error = "1.2.2"
quic-p2p = { version = "~0.7.0" }
rand = "~0.7.3"
rand_chacha = "~0.2.2"
routing = { git = "https://github.com/joshuef/routing.git", branch = "RandoXor" }
self_update = { version = "~0.16.0", default-features = false, features = ["rustls", "archive-tar", "archive-zip", "compression-flate2", "compression-zip-deflate"] }
serde = { version = "1.0.111", features = ["derive", "rc"] }
serde_json = "1.0.53"
structopt = "~0.2.18"
bls = { package = "threshold_crypto", version = "~0.4.0" }
tiny-keccak = "1.5.0"
unwrap = "1.2.1"
crdts = "4.1.0"
ed25519-dalek = "1.0.0-pre.4"
sha2 = "0.8.1"
safe-nd = "~0.11.2"
safe-transfers = "~0.1.0"
ed25519 = "1.0.1"
signature = "1.1.0"
xor_name = "1.1.0"

[dev_dependencies]
maplit = "1.0.1"
tempdir = "~0.3.7"
safe_core = { git = "https://github.com/oetyng/safe_client_libs", branch = "export_tests", features = ["testing"] }
tokio = { version="~0.2.21", features=["rt-core", "blocking", "stream", "rt-util"] }
futures = "~0.3.5"
file-per-thread-logger = { git = "https://github.com/lionel1704/file-per-thread-logger", branch = "allow-uninitialized" }

[[bin]]
name = "safe_vault"
doc = false

[features]
mock_base = ["routing/mock_base", "fxhash", "mock-quic-p2p"]
mock_parsec = ["routing/mock", "mock_base"]
simulated-payouts = ["safe-nd/simulated-payouts", "safe-transfers/simulated-payouts", "safe_core/simulated-payouts"]
