[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
build = "build.rs"
description = "Implementation of the 'Vault' node for the SAFE Network."
documentation = "https://docs.rs/safe_vault"
homepage = "https://maidsafe.net"
license = "GPL-3.0"
name = "safe_vault"
readme = "README.md"
repository = "https://github.com/maidsafe/safe_vault"
version = "0.13.2"

[dependencies]
accumulator = "~0.5.0"
config_file_handler = "~0.6.0"
clap = "~2.14.1"
fs2 = "~0.2.5"
hex = "~0.2.0"
itertools = "~0.5.9"
lru_time_cache = "~0.5.0"
log = "~0.3.6"
maidsafe_utilities = "~0.11.0"
quick-error = "~1.1.0"
rand = "~0.3.14"
routing = { git = "https://github.com/maidsafe/routing.git", branch = "master" }
rust_sodium = "~0.2.0"
serde = "~0.9.12"
serde_derive = "~0.9.12"
serde_json = "~0.9.9"
tiny-keccak = "~1.2.0"
unwrap = "~1.1.0"

[build-dependencies]
hyper = {version = "~0.9.10", optional = true}

[dev-dependencies]
tempdir = "~0.3.5"

[features]
generate-diagrams = ["hyper"]
use-mock-crust = ["routing/use-mock-crust"]

[[test]]
name = "tests"

[[bin]]
name = "safe_vault"
doc = false
