[package]
authors = [ "MaidSafe Developers <dev@maidsafe.net>" ]
description = "Safe Network Client"
documentation = "https://docs.rs/sn_client"
edition = "2018"
homepage = "https://maidsafe.net"
license = "GPL-3.0"
name = "sn_client"
readme = "README.md"
repository = "https://github.com/maidsafe/sn_client"
version = "0.52.11"
keywords = [ "Safe", "Network", "SafeNetwork" ]

[package.metadata.docs.rs]
features = [ "simulated-payouts" ]

[dependencies]
anyhow = "1.0.38"
async-trait = "~0.1.42"
bincode = "1.3.1"
crdts = "~6.3.2"
dirs-next = "2.0.0"
futures = "~0.3.13"
futures-util = "~0.3.13"
log = "~0.4.14"
rand = "~0.7.3"
regex = "1.4.3"
rmp-serde = "~0.15.4"
self_encryption = "~0.21.0"
serde_json = "1.0.62"
sn_data_types = "~0.18.2"
sn_messaging = "16.2.0"
sn_transfers = "0.7.2"
thiserror = "1.0.23"
threshold_crypto = "0.4.0"
url = "2.2.0"
xor_name = "1.1.10"

  [dependencies.bytes]
  version = "1.0.1"
  features = [ "serde" ]

  [dependencies.chrono]
  version = "~0.4.19"
  features = [ "serde" ]

  [dependencies.miscreant]
  version = "~0.5.2"

  [dependencies.qp2p]
  version = "~0.11.7"
  features = [ "no-igd" ]

  [dependencies.serde]
  version = "1.0.123"
  features = [ "derive", "rc" ]

  [dependencies.tiny-keccak]
  version = "2.0.2"
  features = [ "sha3" ]

  [dependencies.tokio]
  version = "1.3.0"
  features = [ "rt", "rt-multi-thread", "sync" ]

[dev-dependencies]
serde_json = "1.0.62"
tracing-subscriber = "~0.2.15"

[features]
default = [ "simulated-payouts" ]
simulated-payouts = [
  "sn_data_types/simulated-payouts",
  "sn_transfers/simulated-payouts",
  "sn_messaging/simulated-payouts"
]
