[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "SAFE Core API library"
documentation = "http://docs.maidsafe.net/safe_core/latest"
homepage = "http://maidsafe.net"
license = "GPL-3.0"
name = "safe_core"
readme = "README.md"
repository = "https://github.com/maidsafe/safe_core"
version = "0.17.0"

[dependencies]
bincode = "~0.5.8"
clippy = {version = "~0.0.78", optional = true}
libc = "~0.2.13"
log = "~0.3.6"
lru_time_cache = "~0.4.0"
maidsafe_utilities = "~0.8.0"
rand = "~0.3.14"
routing = "~0.24.0"
rustc-serialize = "~0.3.19"
safe_network_common = "~0.5.0"
self_encryption = "~0.5.1"
sodiumoxide = "=0.0.10"
time = "~0.1.35"
unwrap = "~1.1.0"

[dev-dependencies]
docopt = "~0.6.81"
regex = "~0.1.71"

[[example]]
bench = false
name = "client_stress_test"

[[example]]
bench = false
name = "self_authentication"

[[example]]
bench = false
name = "safe_client"

[[example]]
bench = false
name = "nfs_api"

[[example]]
bench = false
name = "simulate_browser"

[features]
use-mock-routing = []

[lib]
crate_type = ["staticlib", "dylib", "rlib"]
name = "safe_core"
