[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Implementation of the 'Vault' node for the SAFE Network."
documentation = "https://docs.rs/safe_vault"
edition = "2018"
homepage = "https://maidsafe.net"
license = "GPL-3.0"
name = "safe_vault"
readme = "README.md"
repository = "https://github.com/maidsafe/safe_vault"
version = "0.18.0"

[dependencies]
base64 = "~0.10.1"
# Ensure bincode version is identical to that in SAFE Client Libs and SAFE Network Data.
bincode = "=1.1.4"
bytes = { version = "~0.4.12", features = ["serde"] }
crossbeam-channel = "~0.3.8"
directories = "~2.0.1"
env_logger = "~0.6.1"
fxhash = { version = "~0.2.1", optional = true }
hex = "~0.3.2"
hex_fmt = { version = "~0.3.0", optional = true }
lazy_static = "~1.3.0"
log = "~0.4.6"
pickledb = "~0.4.0"
quic-p2p = { version = "~0.1.1", git = "https://github.com/maidsafe/quic-p2p", optional = true }
quick-error = "~1.2.2"
rand = "~0.6.5"
safe-nd = { version = "~0.1.0", git = "https://github.com/maidsafe/safe-nd" }
serde = { version = "~1.0.93", features = ["derive"] }
serde_json = "~1.0.39"
structopt = "~0.2.16"
tiny-keccak = "~1.4.4"
unwrap = "~1.2.1"

[dev_dependencies]
rand_chacha = "~0.1.1"
tempdir = "~0.3.7"

[[bin]]
name = "safe_vault"
doc = false
required-features = ["quic-p2p"]

[features]
default = ["quic-p2p"]
mock = ["fxhash", "hex_fmt"]
