[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "SAFE Core API library"
documentation = "http://docs.maidsafe.net/safe_core/latest"
homepage = "http://maidsafe.net"
license = "GPL-3.0"
name = "safe_client"
readme = "README.md"
repository = "https://github.com/maidsafe/safe_core"
version = "0.22.0"

[workspace]
members = ["ffi_utils", "safe_app", "safe_authenticator", "safe_core"]

[dev-dependencies]
crossbeam = "~0.2.10"
docopt = "~0.6.86"
regex = "~0.1.80"

[[example]]
bench = false
test = true
name = "email_stress_test"

[[example]]
bench = false
test = true
name = "client_stress_test"

[[example]]
bench = false
test = true
name = "self_authentication"

[[example]]
bench = false
test = true
name = "nfs_api"

[[example]]
bench = false
test = true
name = "simulate_browser"

[[example]]
bench = false
test = true
name = "email"
