[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Implementation of the 'Vault' node for the SAFE Network."
documentation = "https://docs.rs/safe_vault"
edition = "2018"
homepage = "https://maidsafe.net"
license = "GPL-3.0"
name = "safe_vault"
readme = "README.md"
repository = "https://github.com/maidsafe/safe_vault"
version = "0.24.0"

[patch.crates-io]
routing = { git = "https://github.com/oetyng/routing", branch = "farming" }
safe-transfers = { git = "https://github.com/oetyng/safe-transfers", branch = "messaging_refactor" }

[dependencies]
base64 = "~0.10.1"
# Ensure bincode version is identical to that in SAFE Client Libs and SAFE Network Data.
bincode = "1.2.1"
bytes = { version = "~0.5.4", features = ["serde"] }
crossbeam-channel = "~0.4.2"
ctrlc = "3.1.3"
directories = "2.0.1"
fake_clock = "~0.3.0"
flexi_logger = "~0.14.8"
fxhash = { version = "~0.2.1", optional = true }
hex = "~0.3.2"
hex_fmt = "~0.3.0"
lazy_static = "1"
log = "~0.4.7"
mock-quic-p2p = { git = "https://github.com/maidsafe/quic-p2p", branch = "igd-err", optional = true }
pickledb = "~0.4.0"
quick-error = "1.2.2"
rand = "~0.6.5"
rand_chacha = "~0.1.1"
routing_rand_core = { package = "rand_core", version = "~0.5.1" }
routing = { git = "https://github.com/oetyng/routing", branch = "farming" }
safe-nd = { git = "https://github.com/oetyng/safe-nd.git", branch = "messaging_refactor" }
safe-farming = { git = "https://github.com/oetyng/safe-farming.git" }
self_update = { version = "~0.16.0", default-features = false, features = ["rustls", "archive-tar", "archive-zip", "compression-flate2", "compression-zip-deflate"] }
serde = { version = "1.0.97", features = ["derive"] }
serde_json = "1.0.40"
structopt = "~0.2.18"
threshold_crypto = "0.3.2"
tiny-keccak = "1.5.0"
unwrap = "1.2.1"
crdts = "4.1.0"
ed25519-dalek = { version = "0.9.1", features = ["serde"] }
sha2 = "0.8.1"
safe-transfers = "0.1.0"

[dev_dependencies]
maplit = "1.0.1"
tempdir = "~0.3.7"
threshold_crypto = "~0.3.2"

[[bin]]
name = "safe_vault"
doc = false

[features]
mock_base = ["routing/mock_base", "fxhash", "mock-quic-p2p"]
mock_parsec = ["routing/mock", "mock_base"]
simulated-payouts = ["safe-nd/simulated-payouts", "safe-transfers/simulated-payouts"]
