# Copyright 2018 MaidSafe.net limited.
#
# This SAFE Network Software is licensed to you under The General Public License (GPL), version 3.
# Unless required by applicable law or agreed to in writing, the SAFE Network Software distributed
# under the GPL Licence is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. Please review the Licences for the specific language governing
# permissions and limitations relating to use of the SAFE Network Software.

[workspace]
members = ["safe_app", "safe_authenticator", "safe_authenticator_ffi", "safe_core", "tests"]

[patch.crates-io]
# safe-nd = { path = "../safe-nd"}
safe-nd = { git = "https://github.com/oetyng/safe-nd.git", branch = "separate_read_write" }
# safe-nd = { git ="https://github.com/maidsafe/safe-nd", branch="at2", features=["simulated-payouts"] }
# safe-nd = { git ="https://github.com/yoga07/safe-nd", branch="at2", features=["simulated-payouts"] }
safe-transfers = { path = "../safe-transfers"}
# safe-transfers = { git = "https://github.com/oetyng/safe-transfers.git", branch = "separate_read_write" }
self_encryption = {git="https://github.com/maidsafe/self-encryption"}
quic-p2p = {git="https://github.com/maidsafe/quic-p2p"}