[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "SAFE core"
documentation = "https://docs.rs/safe_core"
edition = "2018"
homepage = "https://maidsafe.net"
license = "GPL-3.0"
name = "safe_core"
readme = "README.md"
repository = "https://github.com/maidsafe/safe_client_libs"
version = "0.42.1"


[dependencies]
async-trait = "~0.1.30"
bincode = "1.2.1"
bytes = { version = "~0.5.4", features = ["serde"] }
chrono = { version = "~0.4.0", features = ["serde"] }
crossbeam-channel = "~0.4.2"
directories = "3.0.1"
futures = "~0.3.5"
futures-util = "~0.3.4"
env_logger = "~0.6.2"
lazy_static = "1.4.0"
log = "~0.4.8"
log4rs = { version = "~0.8.3", features = ["toml_format"] }
lru = "~0.5.1"
miscreant = { version = "~0.4.2", features = ["soft-aes"] }
quic-p2p = { git = "https://github.com/maidsafe/quic-p2p.git", branch = "master" }
rand = "~0.7.3"
regex = "1.3.1"
safe-nd = "~0.11.2"
sn_transfers = "~0.2.0"
self_encryption = "~0.19.0"
serde = { version = "1.0.111", features = ["derive", "rc"] }
serde_json = "1.0.53"
serde-value = "~0.5.3"
sha3 = "~0.8.2"
tiny-keccak = "1.5.0"
threshold_crypto = "0.4.0"
tokio = { version="~0.2.21", features=["rt-core", "blocking", "stream", "rt-util"] }
unwrap = "1.2.0"
url = "2.1.0"
ws = "~0.9.1"
crdts = "~4.1.0"
xor_name = "1.1.0"

[dev-dependencies]
serde_json = "1.0.9"

[features]
simulated-payouts = ["safe-nd/simulated-payouts", "sn_transfers/simulated-payouts"]
testing = []

[patch.crates-io]
safe-nd = { git = "https://github.com/maidsafe/safe-nd.git" }
self_encryption = { git = "https://github.com/maidsafe/self_encryption.git", branch = "master" }

[package.metadata.docs.rs]
features = ["simulated-payouts"]
