[package]
authors = [ "MaidSafe Developers <dev@maidsafe.net>" ]
description = "Safe Network Messaging"
edition = "2018"
homepage = "https://maidsafe.net"
license = "MIT OR BSD-3-Clause"
name = "sn_messaging"
readme = "README.md"
repository = "https://github.com/maidsafe/sn_messaging"
version = "8.0.0"

[dependencies]
bincode = "1.2.1"
bytes = "1.0.1"
cookie-factory = "0.3.1"
crdts = "4.3.0"
hex_fmt = "~0.3.0"
multibase = "~0.8.0"
rand = "~0.7.3"
rand_core = "~0.5.1"
rmp-serde = "~0.15.1"
serde_bytes = "0.11.5"
signature = "1.1.0"
sn_data_types = { git = "https://github.com/oetyng/sn_data_types", branch = "split-section-wallet" }
# sn_data_types = "~0.16.0"
thiserror = "1.0.23"
threshold_crypto = "~0.4.0"
xor_name = "1.1.10"

  [dependencies.ed25519-dalek]
  version = "1.0.0-pre.4"
  features = [ "serde" ]

  [dependencies.serde]
  version = "1.0.91"
  features = [ "derive" ]

  [dependencies.tiny-keccak]
  version = "2.0.2"
  features = [ "sha3" ]

[dev-dependencies]
anyhow = "1.0.36"
rand_xorshift = "~0.2.0"

[features]
simulated-payouts = [ "sn_data_types/simulated-payouts" ]
client-only = [ ]
