[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "SAFE Core API library"
documentation = "http://maidsafe.github.io/safe_core/latest/"
homepage = "http://maidsafe.net"
license = "GPL-3.0"
name = "safe_core"
readme = "README.md"
repository = "https://github.com/maidsafe/safe_core"
version = "0.11.0"

[dependencies]
log = "~0.3.5"
lru_time_cache = "~0.2.7"
maidsafe_utilities = "~0.4.0"
mpid_messaging = "~0.2.0"
rand = "~0.3.14"
routing = "~0.11.1"
rustc-serialize = "~0.3.18"
safe_network_common = "~0.0.1"
self_encryption = "~0.3.0"
sodiumoxide = "~0.0.9"
time = "~0.1.34"
xor_name = "~0.1.0"

[dependencies.clippy]
optional = true
version = "~0.0.49"

[dev-dependencies]
docopt = "~0.6.78"
regex = "~0.1.55"

[[example]]
bench = false
name = "client_stress_test"

[[example]]
bench = false
name = "self_authentication"

[[example]]
bench = false
name = "safe_client"

[[example]]
bench = false
name = "rest_api"

[[example]]
bench = false
name = "simulate_browser"

[features]
use-mock-routing = []
