[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "SAFE Core API library"
documentation = "http://docs.maidsafe.net/safe_core/latest"
homepage = "http://maidsafe.net"
license = "GPL-3.0"
name = "safe_core"
readme = "README.md"
repository = "https://github.com/maidsafe/safe_core"
version = "0.22.0"

[dependencies]
clippy = { version = "~0.0.91", optional = true }
config_file_handler = "~0.4.0"
futures = "0.1"
lazy_static = "~0.2.1"
libc = "~0.2.16"
log = "~0.3.6"
lru-cache = "~0.0.7"
maidsafe_utilities = "~0.10.0"
rand = "~0.3.14"
routing = "~0.27.1"
rust_sodium = "~0.1.2"
rustc-serialize = "~0.3.19"
# self_encryption = "~0.7.1"
self_encryption = { git = "https://github.com/madadam/self_encryption.git", branch = "async" }
time = "~0.1.35"
tokio-core = { git = "https://github.com/tokio-rs/tokio-core.git" }
unwrap = "~1.1.0"

[dev-dependencies]
crossbeam = "~0.2.10"
docopt = "~0.6.85"
regex = "~0.1.77"

[[example]]
bench = false
test = false
name = "email_stress_test"

[[example]]
bench = false
test = false
name = "client_stress_test"

[[example]]
bench = false
test = false
name = "self_authentication"

[[example]]
bench = false
test = false
name = "safe_client"

[[example]]
bench = false
test = false
name = "nfs_api"

[[example]]
bench = false
test = false
name = "simulate_browser"

[[example]]
bench = false
test = false
name = "email"

[features]
use-mock-routing = []

[lib]
crate_type = ["staticlib", "rlib", "cdylib"]
name = "safe_core"
