[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "SAFE Core API library"
documentation = "http://maidsafe.github.io/safe_core/latest/"
homepage = "http://maidsafe.net"
license = "GPL-3.0"
name = "safe_core"
readme = "README.md"
repository = "https://github.com/maidsafe/safe_core"
version = "0.14.5"

[dependencies]
bincode = "~0.5.4"
libc = "~0.2.11"
log = "~0.3.6"
lru_time_cache = "~0.3.0"
maidsafe_utilities = "~0.5.4"
rand = "~0.3.14"
routing = "~0.19.1"
rustc-serialize = "~0.3.19"
safe_network_common = "~0.1.1"
self_encryption = "~0.3.1"
sodiumoxide = "~0.0.10"
time = "~0.1.35"
xor_name = "~0.1.0"

[lib]
crate_type = ["staticlib", "dylib", "rlib"]
name = "safe_core"

[dependencies.clippy]
optional = true
version = "~0.0.67"

[dev-dependencies]
docopt = "~0.6.80"
regex = "~0.1.65"

[[example]]
bench = false
name = "client_stress_test"

[[example]]
bench = false
name = "self_authentication"

[[example]]
bench = false
name = "safe_client"

[[example]]
bench = false
name = "nfs_api"

[[example]]
bench = false
name = "simulate_browser"

[features]
use-mock-routing = []
