[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
build = "build.rs"
description = "Implementation of the 'Vault' node for the SAFE Network."
documentation = "https://docs.rs/safe_vault"
homepage = "https://maidsafe.net"
license = "GPL-3.0"
name = "safe_vault"
readme = "README.md"
repository = "https://github.com/maidsafe/safe_vault"
version = "0.18.0"

edition = "2018"

[dependencies]
accumulator = "~0.7.0"
clap = "~2.25.1"
config_file_handler = "~0.11.0"
fake_clock = "~0.2.0"
hex = "~0.3.1"
itertools = "~0.7.8"
log = "~0.4.1"
lru_time_cache = "~0.8.0"
maidsafe_utilities = "~0.16.0"
quick-error = "~1.2.1"
rand = "~0.4.2"
routing = "~0.37.0"
rust_sodium = "~0.10.0"
serde = "~1.0.37"
serde_derive = "~1.0.37"
serde_json = "~1.0.13"
tempdir = "~0.3.7"
tiny-keccak = "~1.3.1"
unwrap = "~1.2.0"

[build-dependencies]
hyper = { version = "~0.11.25", optional = true }

[features]
generate-diagrams = ["hyper"]
use-mock-crust = ["routing/use-mock-crust", "lru_time_cache/fake_clock"]
use-mock-routing = ["lru_time_cache/fake_clock"]
use-mock-crypto = ["routing/use-mock-crypto"]

[[test]]
name = "tests"

[[bin]]
name = "safe_vault"
doc = false
