[package]
authors = [ "MaidSafe Developers <dev@maidsafe.net>" ]
description = "Implementation of the nodes for the Safe Network."
documentation = "https://docs.rs/sn_node"
edition = "2018"
homepage = "https://maidsafe.net"
license = "GPL-3.0"
name = "sn_node"
readme = "README.md"
repository = "https://github.com/maidsafe/sn_node"
version = "0.25.9"

[package.metadata.cargo-udeps.ignore]
development = [ "sn_client", "maplit" ]

[dependencies]
async-log = "2.0.0"
base64 = "~0.10.1"
bincode = "1.2.1"
crossbeam-channel = "~0.4.2"
dirs-next = "1.0.1"
flexi_logger = "~0.16.1"
futures = "~0.3.5"
hex = "~0.3.2"
hex_fmt = "~0.3.0"
lazy_static = "1"
log = "~0.4.7"
pickledb = "~0.4.0"
quick-error = "1.2.2"
rand = "~0.7.3"
rand_chacha = "~0.2.2"
sn_routing = "~0.38.0"
serde_json = "1.0.53"
structopt = "~0.3.17"
tiny-keccak = "1.5.0"
crdts = "4.3.0"
ed25519-dalek = "1.0.0-pre.4"
sha2 = "0.8.1"
# sn_data_types = "~0.11.36"
sn_data_types = { path = "../sn_data_types" }
# sn_transfers = "~0.2.4"
sn_transfers = { path = "../sn_transfers" }
# sn_data_types = { git = "https://github.com/oetyng/sn_data_types", branch = "wallet-actor-model" }
# sn_transfers = { git = "https://github.com/oetyng/sn_transfers", branch = "wallet-actor-model" }
self_encryption = "~0.19.4"
ed25519 = "1.0.1"
signature = "1.1.0"
xor_name = "1.1.0"
sn_launch_tool = "~0.0.5"
dashmap = "3.11.10"

  [dependencies.bytes]
  version = "~0.5.4"
  features = [ "serde" ]

  [dependencies.fxhash]
  version = "~0.2.1"
  optional = true

  [dependencies.self_update]
  version = "~0.16.0"
  default-features = false
  features = [
  "rustls",
  "archive-tar",
  "archive-zip",
  "compression-flate2",
  "compression-zip-deflate"
]

  [dependencies.serde]
  version = "1.0.111"
  features = [ "derive", "rc" ]

  [dependencies.bls]
  package = "threshold_crypto"
  version = "~0.4.0"

  [dependencies.tokio]
  version = "~0.2.5"
  features = [ "macros", "fs", "sync" ]

[dev_dependencies]
maplit = "1.0.1"
tempdir = "~0.3.7"
futures = "~0.3.5"

  [dev_dependencies.sn_client]
  version = "0.44.3"
  features = [ "simulated-payouts" ]
  # git = "https://github.com/oetyng/sn_client"
  # branch = "wallet-actor-model"
  path="../sn_client"

  [dev_dependencies.tokio]
  version = "~0.2.21"
  features = [ "rt-core", "blocking", "stream", "rt-util", "rt-threaded" ]

[[bin]]
name = "sn_node"
doc = false

[features]
default = [ "simulated-payouts" ]
simulated-payouts = [
  "sn_data_types/simulated-payouts",
  "sn_transfers/simulated-payouts",
  "sn_client/simulated-payouts",
]
chaos = [ ]

# [patch.crates-io]
# sn_client = { git = "https://github.com/oetyng/sn_client", branch = "wallet-actor-model" }
# sn_data_types = { git = "https://github.com/oetyng/sn_data_types", branch = "wallet-actor-model" }
# sn_transfers = { git = "https://github.com/oetyng/sn_transfers", branch = "wallet-actor-model" }
