[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Implementation of the nodes for the Safe Network."
documentation = "https://docs.rs/sn_node"
edition = "2018"
homepage = "https://maidsafe.net"
license = "GPL-3.0"
name = "sn_node"
readme = "README.md"
repository = "https://github.com/maidsafe/sn_node"
version = "0.24.0"

[dependencies]
async-log = "2.0.0"
base64 = "~0.10.1"
# Ensure bincode version is identical to that in sn_client and sn_data_types.
bincode = "1.2.1"
bytes = { version = "~0.5.4", features = ["serde"] }
crossbeam-channel = "~0.4.2"
ctrlc = "3.1.3"
dirs-next = "1.0.1"
sn_fake_clock = "~0.4.0"
flexi_logger = "~0.16.1"
futures = "~0.3.5"
fxhash = { version = "~0.2.1", optional = true }
hex = "~0.3.2"
hex_fmt = "~0.3.0"
lazy_static = "1"
log = "~0.4.7"
pickledb = "~0.4.0"
quick-error = "1.2.2"
rand = "~0.7.3"
rand_chacha = "~0.2.2"
sn_routing = { git = "https://github.com/yoga07/sn_routing", branch = "start-up" }
self_update = { version = "~0.16.0", default-features = false, features = ["rustls", "archive-tar", "archive-zip", "compression-flate2", "compression-zip-deflate"] }
serde = { version = "1.0.111", features = ["derive", "rc"] }
serde_json = "1.0.53"
structopt = "~0.3.17"
bls = { package = "threshold_crypto", version = "~0.4.0" }
tiny-keccak = "1.5.0"
unwrap = "1.2.1"
crdts = "4.2.0"
ed25519-dalek = "1.0.0-pre.4"
sha2 = "0.8.1"
sn_data_types = "~0.11.31"
sn_transfers = "~0.2.4"
ed25519 = "1.0.1"
signature = "1.1.0"
tokio = { version = "~0.2.5", features = ["macros", "fs", "sync"] }
xor_name = "1.1.0"
sn_launch_tool = { git = "https://github.com/maidsafe/sn_launch_tool.git" }

[dev_dependencies]
maplit = "1.0.1"
tempdir = "~0.3.7"
sn_client = { git = "https://github.com/maidsafe/sn_client" }
tokio = { version="~0.2.21", features=["rt-core", "blocking", "stream", "rt-util", "rt-threaded"] }
futures = "~0.3.5"

[[bin]]
name = "sn_node"
doc = false

[features]
simulated-payouts = ["sn_data_types/simulated-payouts", "sn_transfers/simulated-payouts", "sn_client/simulated-payouts"]
chaos = []
