[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "SAFE Core API library"
documentation = "http://maidsafe.github.io/safe_core/latest/"
homepage = "http://maidsafe.net"
license = "GPL-3.0"
name = "safe_core"
readme = "README.md"
repository = "https://github.com/maidsafe/safe_core"
version = "0.13.1"

[dependencies]
clippy = {version = "~0.0.62", optional = true}
log = "~0.3.6"
lru_time_cache = "~0.2.7"
maidsafe_utilities = "~0.5.1"
rand = "~0.3.14"
routing = "~0.13.0"
rustc-serialize = "~0.3.19"
safe_network_common = "~0.1.1"
self_encryption = "~0.3.0"
sodiumoxide = "~0.0.10"
time = "~0.1.35"
xor_name = "~0.1.0"

[dev-dependencies]
docopt = "~0.6.78"
regex = "~0.1.61"

[[example]]
bench = false
name = "client_stress_test"

[[example]]
bench = false
name = "self_authentication"

[[example]]
bench = false
name = "safe_client"

[[example]]
bench = false
name = "rest_api"

[[example]]
bench = false
name = "simulate_browser"

[features]
use-mock-routing = []
use-mock-crust = ["routing/use-mock-crust"]
