[package]
authors = [ "MaidSafe Developers <dev@maidsafe.net>" ]
description = "Implementation of the nodes for the Safe Network."
documentation = "https://docs.rs/sn_node"
edition = "2018"
homepage = "https://maidsafe.net"
license = "GPL-3.0"
name = "sn_node"
readme = "README.md"
repository = "https://github.com/maidsafe/sn_node"
version = "0.31.0"

[package.metadata.cargo-udeps.ignore]
development = [ "sn_client", "maplit" ]

[dependencies]
async-log = "2.0.0"
base64 = "~0.10.1"
bincode = "1.2.1"
dirs-next = "1.0.1"
flexi_logger = "~0.16.1"
futures = "~0.3.5"
hex = "~0.3.2"
hex_fmt = "~0.3.0"
lazy_static = "1"
log = "~0.4.7"
pickledb = "~0.4.0"
rand = "~0.7.3"
rand_chacha = "~0.2.2"
serde_json = "1.0.53"
structopt = "~0.3.17"
crdts = "4.3.0"
ed25519-dalek = "1.0.0-pre.4"
sn_routing = "~0.52.0"
sn_transfers = "~0.6.0"
sn_messaging = "^9.0.0"
sn_data_types = "~0.17.0"
ed25519 = "1.0.1"
signature = "1.1.10"
xor_name = "1.1.10"
sn_launch_tool = "~0.0.15"
dashmap = "3.11.10"
thiserror = "1.0.23"
itertools = "0.10.0"
async-trait = "0.1.42"

  [dependencies.bytes]
  version = "1.0.1"
  features = [ "serde" ]

  [dependencies.fxhash]
  version = "~0.2.1"
  optional = true

  [dependencies.self_update]
  version = "~0.16.0"
  default-features = false
  features = [
  "rustls",
  "archive-tar",
  "archive-zip",
  "compression-flate2",
  "compression-zip-deflate"
]

  [dependencies.serde]
  version = "1.0.111"
  features = [ "derive", "rc" ]

  [dependencies.bls]
  package = "threshold_crypto"
  version = "~0.4.0"

  [dependencies.tokio]
  version = "1.3.0"
  features = [ "macros", "fs", "sync", "io-util" ]

[dev_dependencies]
maplit = "1.0.1"
tempdir = "~0.3.7"
futures = "~0.3.8"

  [dev_dependencies.tokio]
  version = "1.3.0"
  features = [ "rt", "rt-multi-thread" ]

[[bin]]
name = "sn_node"
doc = false

[features]
default = [ "simulated-payouts" ]
simulated-payouts = [
  "sn_data_types/simulated-payouts",
  "sn_transfers/simulated-payouts",
  "sn_messaging/simulated-payouts"
]
chaos = [ ]
