[package]
authors = [ "MaidSafe Developers <dev@maidsafe.net>" ]
description = "The Safe Network Core. API message definitions, routing and nodes, client core api."
documentation = "https://docs.rs/sn_node"
edition = "2018"
homepage = "https://maidsafe.net"
license = "GPL-3.0"
name = "safe_network"
readme = "README.md"
repository = "https://github.com/maidsafe/safe_network"
version = "0.7.10"

[profile.release]
incremental = true

[[bin]]
name = "sn_node"
doc = false
path = "src/node/bin/sn_node.rs"

[[bin]]
name = "launch_network"
doc = false
path = "src/node/bin/launch_network.rs"

[features]
default = [ "testing" ]
testing = [ ]
chaos = [ ]
always-joinable = [ ]

[dependencies]
base64 = "~0.10.1"
hex = "~0.3.2"
lazy_static = "1"
pickledb = "~0.4.0"
rand = "~0.7.3"
rand_chacha = "~0.2.2"
serde_json = "1.0.53"
structopt = "~0.3.17"
ed25519 = "1.0.1"
signature = "1.1.10"
xor_name = "1.1.10"
sn_launch_tool = "~0.2.0"
thiserror = "1.0.23"
itertools = "0.10.0"
async-trait = "0.1.42"
secured_linked_list = "~0.3.0"
bls_dkg = "~0.5.0"
cookie-factory = "0.3.1"
hex_fmt = "~0.3.0"
multibase = "~0.8.0"
rand_core = "~0.5.1"
serde_bytes = "0.11.5"
qp2p = "~0.12.0"
resource_proof = "0.8.0"
anyhow = "1.0.40"
bincode = "1.3.1"
crdts = "6.3.3"
dirs-next = "2.0.0"
futures = "~0.3.13"
futures-util = "~0.3.13"
regex = "1.4.3"
rmp-serde = "~0.15.4"
self_encryption = "~0.25.0"
uhttp_uri = "~0.5"
urlencoding = "1.1.1"
url = "2.2.0"
dashmap = "~4.0.2"
lru="0.6.5"
tracing-appender = "~0.1.2"
tracing-subscriber = "~0.2.15"
tracing-futures = "~0.2.5"
tracing= "~0.1.26"
exponential-backoff = "1.0.0"
async-recursion = "0.3.2"
sled = "0.34.6"
sysinfo = "0.19.0"

  [dependencies.ed25519-dalek]
  version = "1.0.0"
  features = [ "serde" ]

  [dependencies.tiny-keccak]
  version = "2.0.2"
  features = [ "sha3" ]

  [dependencies.bytes]
  version = "1.0.1"
  features = [ "serde" ]

  [dependencies.fxhash]
  version = "~0.2.1"
  optional = true

  [dependencies.self_update]
  version = "~0.16.0"
  default-features = false
  features = [
  "rustls",
  "archive-tar",
  "archive-zip",
  "compression-flate2",
  "compression-zip-deflate"
]


  [dependencies.serde]
  version = "1.0.111"
  features = [ "derive", "rc" ]

  [dependencies.bls]
  package = "blsttc"
  version = "2.0.1"

  [dependencies.tokio]
  version = "1.8.0"
  features = [ "macros", "fs", "sync", "io-util", "rt", "rt-multi-thread" ]

[dev-dependencies]
anyhow = "1"
assert_matches = "1.3"
proptest = "0.10.1"
rand_xorshift = "~0.2.0"
structopt = "~0.3.17"
tempfile = "3.2.0"
yansi = "~0.5.0"

  [dev-dependencies.rand]
  version = "~0.7.3"
  features = [ "small_rng" ]

  [dev-dependencies.tokio-util]
  version = "~0.6.7"
  features = [ "time" ]
