[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "SAFE core"
documentation = "https://docs.rs/safe_core"
homepage = "https://maidsafe.net"
license = "GPL-3.0"
name = "safe_core"
readme = "README.md"
repository = "https://github.com/maidsafe/safe_client_libs"
version = "0.31.0"

[dependencies]
base64 = "~0.9.0"
chrono = { version = "~0.4.0", features = ["serde"] }
config_file_handler = "~0.9.0"
ffi_utils = "~0.7.0"
fs2 = "~0.4.3"
futures = "~0.1.17"
lazy_static = "~1.0.0"
log = "~0.4.1"
lru-cache = "~0.1.1"
maidsafe_utilities = "~0.15.0"
rand = "~0.3.18"
routing = "~0.35.0"
rust_sodium = "~0.7.0"
self_encryption = "~0.12.0"
serde = "~1.0.27"
serde_derive = "~1.0.27"
tiny-keccak = "~1.3.1"
tokio-core = "~0.1.12"
unwrap = "~1.1.0"

[dev-dependencies]
serde_json = "~1.0.9"

[features]
use-mock-routing = []
testing = []
