[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "The Safe Network Node Implementation."
documentation = "https://docs.rs/sn_node"
edition = "2021"
homepage = "https://maidsafe.net"
license = "GPL-3.0"
name = "sn_node"
readme = "README.md"
repository = "https://github.com/maidsafe/safe_network"
version = "0.71.0"

[[bench]]
name = "data_storage"
harness = false

[features]
default = [ "statemap" ]
limit-network-size = []
chaos = []
unstable-wiremsg-debuginfo = []
# Needs to be built with RUSTFLAGS="--cfg tokio_unstable"
tokio-console = ["console-subscriber"]
otlp = [ "opentelemetry", "opentelemetry-otlp", "opentelemetry-semantic-conventions", "tracing-opentelemetry" ]
statemap = []

[dependencies]
backoff = { version = "~0.4.0", features = [ "tokio" ] }
base64 = "~0.13.0"
bincode = "1.3.1"
bls = { package = "blsttc", version = "8.0" }
bytes = { version = "1.0.1", features = ["serde"] }
chrono = "0.4.19"
color-eyre = "~0.6.0"
console-subscriber = { version = "~0.1.0", optional = true }
crdts = { version = "7.2", default-features=false, features = ["merkle"] }
custom_debug = "~0.5.0"
dashmap = {version = "5.1.0", features = [ "serde" ]}
dirs-next = "2.0.0"
ed25519 = { version = "1.2.0", features = ["serde_bytes"] }
ed25519-dalek = { version = "1.0.0", features = ["serde"] }
eyre = "~0.6.5"
file-rotate = "~0.6.0"
futures = "~0.3.13"
hex = "~0.4.3"
hex_fmt = "~0.3.0"
itertools = "~0.10.0"
lazy_static = "1"
multibase = "~0.9.1"
num_cpus = "1.13.0"
opentelemetry = { version = "0.17", features = ["rt-tokio"], optional = true }
opentelemetry-otlp = { version = "0.10", optional = true }
opentelemetry-semantic-conventions = { version = "0.9.0", optional = true }
qp2p = { git = "https://github.com/b-zee/qp2p", branch = "feat-qp2p-6" }
rand = "~0.8"
rand-07 = { package = "rand", version = "~0.7.3" }
rayon = "1.5.1"
rmp-serde = "1.0.0"
self_encryption = "~0.27.5"
sn_consensus = "3.1.2"
sn_dbc = { version = "8.1.0", features = ["serdes"] }
sn_dysfunction = { path = "../sn_dysfunction", version = "^0.14.0" }
sn_interface = { path = "../sn_interface", version = "^0.15.0" }
sn_sdkg = "3.0.0"
serde = { version = "1.0.111", features = ["derive", "rc"] }
serde_bytes = "~0.11.5"
serde_json = "1.0.53"
signature = "1.1.10"
clap = { version = "3.0.0", features = ["derive"] }
clap_complete = { version = "3.0.0" }
strum = "0.24"
strum_macros = "0.24"
sysinfo = "~0.23.2"
tempfile = "3.2.0"
thiserror = "1.0.23"
tiny-keccak = { version = "2.0.2", features = ["sha3"] }
tracing = "0.1"
tracing-core = "0.1"
tracing-appender = "~0.2.0"
tracing-opentelemetry = { version = "0.17", optional = true }
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
uluru="3.0.0"
url = "2.2.0"
walkdir = "2"
xor_name = "~5.0.0"

[dependencies.self_update]
version = "0.32"
default-features = false
features = ["archive-tar", "archive-zip", "compression-flate2", "compression-zip-deflate", "rustls"]

[dependencies.tokio]
version = "1.17.0"
features = ["fs", "io-util", "macros", "rt-multi-thread", "sync"]

[dev-dependencies]
criterion = { version = "0.4", features = ["async_tokio"] }
assert_matches = "1.3"
ctor = "~0.1.20"
proptest = "1.0.0"
rand = { version = "~0.8.5", features = ["small_rng"] }
tokio-util = { version = "~0.7", features = ["time"] }
walkdir = "2"
sn_interface = { path = "../sn_interface", version = "^0.15.0", features= ["test-utils", "proptest"] }

[dev-dependencies.cargo-husky]
version = "1.5.0"
default-features = false # Disable features which are enabled by default
features = ["precommit-hook", "run-cargo-clippy", "run-cargo-fmt"]

[package.metadata.cargo-udeps.ignore]
development = ["cargo-husky"]
