[package]
name = "sn_api"
version = "0.19.1"
description = "Safe API"
authors = ["bochaco <gabrielviganotti@gmail.com>", "Josh Wilson <joshuef@gmail.com>"]
license = "MIT OR BSD-3-Clause"
repository = "https://github.com/maidsafe/sn_api"
include = ["Cargo.toml", "src/api/*", "src/lib.rs"]
edition = "2018"

[dependencies]
async-trait = "~0.1.42"
ed25519-dalek = { version = "1.0.1", features = [ "serde" ]}
bincode = "1.3.1"
chrono = "~0.4.19"
dirs-next = "2.0.0"
env_logger = "~0.8.3"
futures = "~0.3.12"
qjsonrpc = { path = "../qjsonrpc", version = "~0.1.1" }
lazy_static = "1.4.0"
log = "~0.4.14"
mime_guess = "2.0.3"
multibase = "~0.9.1"
rand = "~0.7.3"
rand_core = "~0.5.1"
relative-path = "1.3.2"
sn_client = "~0.47.1"
sn_data_types = "~0.15.0"
serde = "1.0.123"
serde_json = "1.0.62"
thiserror = "1.0.23"
threshold_crypto = "~0.4.0"
tokio = { version = "~0.2.25", features = ["rt-core"] }
url = "2.2.0"
urlencoding = "1.1.1"
walkdir = "2.3.1" #ffi utils needs this version
uhttp_uri = "~0.5.1"
xor_name = "1.1.10"
pbkdf2 = { version = "~0.7.0", default-features = false }
hmac = "~0.10.1"
sha3 = "~0.9.1"

  [dependencies.tiny-keccak]
  version = "2.0.2"
  features = [ "sha3" ]

[features]
authenticator = []
authd_client = []
app = []
simulated-payouts = ["sn_client/simulated-payouts"]
default = ["simulated-payouts", "authenticator", "authd_client", "app"]

[dev-dependencies]
anyhow = "1.0.38"
tokio = { version = "~0.2.25", features = ["macros"] }
proptest = "0.10.1"
