[package]
name = "sn_api"
version = "0.50.2"
description = "Safe API"
authors = [
  "bochaco <gabrielviganotti@gmail.com>",
  "Josh Wilson <joshuef@gmail.com>"
]
license = "MIT OR BSD-3-Clause"
repository = "https://github.com/maidsafe/sn_api"
include = [ "Cargo.toml", "src/*" ]
edition = "2021"

[dependencies]
bincode = "1.3.1"
color-eyre = "~0.5"
dirs-next = "2.0.0"
env_logger = "~0.8"
futures = "~0.3"
hex = "~0.4"
hmac = "~0.10"
lazy_static = "1.4.0"
log = "~0.4"
mime_guess = "2.0.3"
multibase = "~0.9"
qjsonrpc = "~0.2"
rand = "~0.7"
rand_core = "~0.5"
relative-path = "1.3.2"
rmp-serde = "~0.15"
serde = "1.0.123"
serde_json = "1.0.62"
sha3 = "~0.9"
safe_network = { path = "../sn", version ="^0.52.7"}
thiserror = "1.0.23"
time = { version = "0.3.4", features = ["formatting"] }
tracing = "~0.1.26"
uhttp_uri = "~0.5"
url = "2.2.0"
urlencoding = "1.1.1"
walkdir = "2.3.1"
xor_name = "3.0.0"

  [dependencies.bls]
  package = "blsttc"
  version = "3.1.0"

  [dependencies.bytes]
  version = "1.0.1"
  features = [ "serde" ]

  [dependencies.ed25519-dalek]
  version = "1.0.1"
  features = [ "serde" ]

  [dependencies.pbkdf2]
  version = "~0.7"
  default-features = false

  [dependencies.tokio]
  version = "1.6.0"
  features = [ "rt" ]

  [dependencies.tiny-keccak]
  version = "2.0.2"
  features = [ "sha3" ]

[features]
authenticator = [ ]
authd_client = [ ]
app = [ ]
testing = [ ]
default = [ "testing", "authenticator", "authd_client", "app" ]

[dev-dependencies]
assert_matches = "1.3"
anyhow = "1.0.38"
proptest = "~0.10"
tracing-subscriber = "0.3.1"

  [dev-dependencies.tokio]
  version = "1.6.0"
  features = [ "macros" ]
