[package]
name = "sn_cli"
version = "0.25.0"
description = "Safe CLI"
authors = ["bochaco <gabrielviganotti@gmail.com>", "Josh Wilson <joshuef@gmail.com>"]
publish = false
license = "MIT OR BSD-3-Clause"
default-run = "safe"
repository = "https://github.com/maidsafe/sn_api"
edition = "2018"

[[bin]]
name = "safe"
path = "main.rs"

[dependencies]
ansi_term = "~0.12"
async-std = "1.9.0"
chrono = "~0.4"
dirs-next = "2.0.0"
ed25519-dalek = { version = "1.0.1", features = [ "serde" ]}
env_logger = "~0.8"
envy = "~0.4"
hex = "~0.4"
human-panic = "1.0.3"
log = "~0.4"
pretty-hex = "~0.2"
prettytable-rs = "~0.8"
rand = "~0.7"
relative-path = "1.3.2"
reqwest = { version = "~0.11", default-features=false, features = ["rustls-tls"], optional = true }
rpassword = "5.0.1"
sn_launch_tool = "~0.2"
serde = "1.0.123"
serde_json = "1.0.62"
serde_yaml = "~0.8"
shrust = "~0.0.7"
structopt = "~0.3"
anyhow = "1.0.38"
tokio = { version = "1.3.0", features = ["macros"] }
isatty = "~0.1"
num-traits = "~0.2"
indicatif = { git = "https://github.com/mibac138/indicatif", branch = "mpb-tick" }
console = "~0.14"
percent-encoding = "2.1.0"
xor_name = "1.1.10"

[features]
default = ["simulated-payouts", "self-update"]
simulated-payouts = ["sn_api/simulated-payouts"]
self-update = ["reqwest", "self_update"]


[dependencies.sn_api]
path = "../sn_api"
default-features = false
features = ["app", "authd_client", "simulated-payouts"]

[dependencies.self_update]
version = "~0.23"
default-features = false
features = ["rustls", "archive-tar", "archive-zip", "compression-flate2", "compression-zip-deflate"]
optional = true

[dev-dependencies]
assert_cmd = "~0.11"
duct = "~0.12"
predicates = "1.0.0"
sn_data_types = "~0.18"
criterion = "~0.3"
walkdir = "2.3.1"
multibase = "~0.6"
sn_cmd_test_utilities = { path = "../sn_cmd_test_utilities" }
xor_name = "1"

# Our various benchmakrs.
# Harness=false disables rust baked in bench to use criterion instead.
[[bench]]
name = "put"
harness = false
[[bench]]
name = "keys"
harness = false
[[bench]]
name = "wallet"
harness = false
