# Copyright 2019 MaidSafe.net limited.
#
# This SAFE Network Software is licensed to you under The General Public License (GPL), version 3.
# Unless required by applicable law or agreed to in writing, the SAFE Network Software distributed
# under the GPL Licence is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. Please review the Licences for the specific language governing
# permissions and limitations relating to use of the SAFE Network Software.

[package]
name = "safe-cli"
version = "0.5.0"
description = "SAFE CLI"
authors = ["bochaco <gabrielviganotti@gmail.com>", "Josh Wilson <joshuef@gmail.com>", "Calum Craig <calum.craig@maidsafe.net>", "Chris O'Neil <chris.oneil@gmail.com>"]
publish = false
license = "GPL-3.0"
repository = "https://github.com/maidsafe/safe-cli"
edition = "2018"

[[bin]]
name = "safe"
path = "main.rs"

[dependencies]
safe-api = { path = "../safe-api" }
log = "0.4.6"
structopt = "0.2.15"
env_logger = "0.6.0"
rand = "0.6.5"
prettytable-rs = "^0.8"
serde = "1.0.91"
serde_json = "1.0.39"
human-panic = "1.0.1"
relative-path = "0.4.0"
self_update = "0.5.1"
directories = "~2.0.1"

[features]
mock-network = ["safe-api/mock-network"]
fake-auth = ["safe-api/fake-auth"]
scl-mock = ["safe-api/scl-mock"]

[dev-dependencies]
safe-nd = "~0.4.0"
pretty_assertions = "0.6.1"
predicates = "1.0.0"
assert_cmd = "0.11.1"
duct = "0.12.0"
unwrap = "~1.2.1"

[dev-dependencies.cargo-husky]
version = "1"
default-features = false # Disable features which are enabled by default
features = ["precommit-hook","user-hooks"]
