[package]
name = "safe_authenticator_jni"
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "SAFE Authenticator JNI wrapper"
homepage = "https://maidsafe.net"
license = "GPL-3.0"
repository = "https://github.com/maidsafe/safe_client_libs"
version = "0.1.0"

[dependencies]
ffi_utils = "~0.8.0"
jni = "~0.10.1"
safe_core = { path = "../safe_core", version = "~0.31.0" }
unwrap = "~1.2.0"

[dependencies.safe_authenticator]
path = "../safe_authenticator"
version = "~0.8.0"
features = ["bindings"]

[lib]
crate_type = ["cdylib"]

[features]
use-mock-routing = ["testing", "safe_core/use-mock-routing", "safe_authenticator/use-mock-routing"]
testing = ["safe_core/testing", "safe_authenticator/testing"]
