[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "SAFE App"
documentation = "https://docs.rs/safe_app"
homepage = "https://maidsafe.net"
license = "GPL-3.0"
name = "safe_app"
readme = "README.md"
repository = "https://github.com/maidsafe/safe_client_libs"
version = "0.6.0"
build = "build.rs"

[dependencies]
config_file_handler = "~0.9.0"
ffi_utils = { path = "../ffi_utils", version = "~0.5.0" }
futures = "~0.1.17"
log = "~0.4.1"
maidsafe_utilities = "~0.15.0"
rand = "~0.3.18"
routing = "~0.35.0"
rust_sodium = "~0.7.0"
serde = "~1.0.27"
serde_derive = "~1.0.27"
safe_authenticator = { path = "../safe_authenticator", version = "~0.6.0", optional = true }
safe_core = { path = "../safe_core", version = "~0.29.0" }
self_encryption = "~0.12.0"
tiny-keccak = "~1.3.1"
tokio-core = "~0.1.12"
unwrap = "~1.1.0"
# jni = { version = "~0.9.3", optional = true }
jni = { git = "https://github.com/prevoty/jni-rs", optional = true }

[dev-dependencies.safe_authenticator]
path = "../safe_authenticator"
version = "~0.6.0"
features = ["testing"]

[dev-dependencies.safe_core]
path = "../safe_core"
version = "~0.29.0"
features = ["testing"]

[build-dependencies]
ffi_utils = { path = "../ffi_utils", version = "~0.5.0" }
routing = "~0.33.2"
rust_sodium = "~0.5.0"
safe_bindgen = { git = "https://github.com/maidsafe/safe_bindgen.git" }
unwrap = "~1.1.0"

[features]
use-mock-routing = ["testing", "safe_core/use-mock-routing", "safe_authenticator/use-mock-routing"]
testing = ["safe_core/testing", "safe_authenticator/testing"]
bindings = ["safe_core/bindings"]
bindings-jni = ["jni"]

[lib]
crate_type = ["staticlib", "rlib", "cdylib"]
