[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "SAFE App"
documentation = "https://docs.rs/safe_app"
homepage = "https://maidsafe.net"
license = "GPL-3.0"
name = "safe_app"
readme = "README.md"
repository = "https://github.com/maidsafe/safe_client_libs"
version = "0.1.0"

[dependencies]
config_file_handler = "~0.7.0"
ffi_utils = { path = "../ffi_utils", version = "~0.1.0" }
futures = "~0.1.14"
log = "~0.3.7"
lru-cache = "~0.1.0"
maidsafe_utilities = "~0.13.0"
rand = "~0.3.15"
routing = { git = "https://github.com/madadam/routing", branch = "entry-errors" }
#routing = "~0.31.0"
rust_sodium = "~0.3.0"
serde = "~1.0.9"
serde_derive = "~1.0.9"
safe_core = { path = "../safe_core", version = "~0.24.0" }
safe_authenticator = { path = "../safe_authenticator", version = "~0.1.0", optional = true }
self_encryption = "~0.10.0"
tiny-keccak = "~1.2.1"
tokio-core = "~0.1.8"
unwrap = "~1.1.0"

[dev-dependencies]
safe_authenticator = { path = "../safe_authenticator", version = "~0.1.0" }

[features]
use-mock-routing = ["safe_core/use-mock-routing"]
testing = ["safe_authenticator", "safe_authenticator/testing", "safe_core/testing"]

[lib]
crate_type = ["staticlib", "rlib", "cdylib"]
