[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "SAFE App"
documentation = "https://docs.rs/safe_app"
homepage = "https://maidsafe.net"
license = "GPL-3.0"
name = "safe_app"
readme = "README.md"
repository = "https://github.com/maidsafe/safe_client_libs"
version = "0.3.0"

[dependencies]
config_file_handler = "~0.8.1"
ffi_utils = { path = "../ffi_utils", version = "~0.2.0" }
futures = "~0.1.15"
log = "~0.3.7"
lru-cache = "~0.1.0"
maidsafe_utilities = "~0.14.0"
rand = "~0.3.16"
routing = "~0.33.0"
rust_sodium = "~0.5.0"
serde = "~1.0.11"
serde_derive = "~1.0.11"
safe_core = { path = "../safe_core", version = "~0.26.0" }
safe_authenticator = { path = "../safe_authenticator", version = "~0.3.0", optional = true }
self_encryption = "~0.11.0"
tiny-keccak = "~1.3.1"
tokio-core = "~0.1.9"
unwrap = "~1.1.0"

[dev-dependencies]
safe_authenticator = { path = "../safe_authenticator", version = "~0.3.0" }

[features]
use-mock-routing = ["safe_core/use-mock-routing"]
testing = ["safe_authenticator", "safe_authenticator/testing", "safe_core/testing"]

[lib]
crate_type = ["staticlib", "rlib", "cdylib"]
