[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "The Safe Network Tesnet Starter."
documentation = "https://docs.rs/sn_node"
edition = "2021"
homepage = "https://maidsafe.net"
license = "GPL-3.0"
name = "testnet"
readme = "README.md"
repository = "https://github.com/maidsafe/safe_network"
version = "0.1.0"


[features]
default = []

[[bin]]
path="bin.rs"
name="testnet"



[dependencies]
color-eyre = "0.6.0"
console-subscriber = { version = "0.1.0", optional = true }
eyre = "0.6.5"
structopt = "~0.3.17"
safe_network = { path = "../sn", version = "^0.58.0" }
dirs-next = "2.0.0"
sn_launch_tool = "~0.9.6"
tracing = "~0.1.26"
tracing-core = "0.1.21"
tracing-appender = "0.2.0"
tracing-subscriber = { version = "0.3.1", features = ["env-filter", "json"] }

[dependencies.tokio]
version = "~1.17.0"
features = ["fs", "io-util", "macros", "rt", "rt-multi-thread", "sync"]
