[package]
name = "safe-authd"
version = "0.0.1"
description = "SAFE Authenticator (daemon)"
authors = ["bochaco <gabrielviganotti@gmail.com>"]
publish = false
license = "MIT OR BSD-3-Clause"
repository = "https://github.com/maidsafe/safe-api"
edition = "2018"

[[bin]]
name = "safe-authd"
path = "main.rs"

[dependencies]
directories = "1.0.2"
env_logger = "0.6.0"
futures = "~0.1.21"
human-panic = "1.0.1"
jsonrpc-quic = { path = "../jsonrpc-quic" }
log = "0.4.6"
quinn = "~0.3.0"
rcgen = "0.2"
safe-api = { path = "../safe-api" }
self_update = { git = "https://github.com/bochaco/self_update", branch = "feat-s3-backend" }
serde = "1.0.91"
serde_json = "1.0.41"
slog = "2.1"
slog-term = "2"
structopt = "0.2.15"
tokio = "0.1.6"
tokio-current-thread = "0.1"
tokio-reactor = "0.1.1"
url = "1.7.2"
urlencoding = "1.0.0"

[target.'cfg(not(target_os = "windows"))'.dependencies]
daemonize = "~0.4.1"

[target.'cfg(target_os = "windows")'.dependencies]
windows-service = "0.2.0"

[features]
mock-network = ["safe-api/mock-network"]

[dev-dependencies]
unwrap = "~1.2.1"

[dev-dependencies.cargo-husky]
version = "1"
default-features = false # Disable features which are enabled by default
features = ["precommit-hook","user-hooks"]
