name: Run All Tests on Arm

on:
  schedule:
    - cron:  '0 22 * * *'

env:
  RUST_BACKTRACE: 1

jobs:
  tests:
    if: "!startsWith(github.event.pull_request.title, 'Automated version bump')"
    name: Run all test categories
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        target: [arm-unknown-linux-musleabi, armv7-unknown-linux-musleabihf, aarch64-unknown-linux-musl]
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        id: toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: true

      - name: Install cross
        run: cargo install cross

      - name: Build all safe_network targets
        run: cross build --all-targets --release --target ${{ matrix.target }}

      - name: Run Messaging tests
        run: cross test --release --target ${{ matrix.target }} messaging

      - name: Run Node tests
        run: cross test --release --target ${{ matrix.target }} node

      - name: Run Doc tests
        run: cross test --release --target ${{ matrix.target }} client --doc

      - name: Run Routing tests
        run: cross test --release --target ${{ matrix.target }} routing

      - name: Run URL tests
        run: cross test --release --target ${{ matrix.target }} url

      - name: Run Data Types tests
        run: cross test --release --target ${{ matrix.target }} types
