name: Benchmarks

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CARGO_INCREMENTAL: 0 # bookkeeping for incremental builds has overhead, not useful in CI.
  NODE_COUNT: 15

jobs:
  benchmarks:
    if: "!startsWith(github.event.pull_request.title, 'Automated version bump')"
    name: Run performance regression check (EC2)
    # right now only ubuntu, running on multiple systems would require many pushes...\
    # perhaps this can be done with one consolidation action in the future, pulling down all results and pushing
    # once to the branch..
    runs-on: self-hosted
    env:
      CARGO_BUILD_TARGET: x86_64-unknown-linux-musl
      CARGO_HOME: /mnt/data/cargo
      TMPDIR: /mnt/data/tmp
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: true
      - run: cargo install cargo-criterion

      # Download previous benchmark result from cache (if exists)
      - name: Download previous benchmark data
        uses: actions/cache@v1
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark

      - name: ubuntu install ripgrep
        run: sudo apt-get -y install ripgrep

      # Node benchmark, which does not need the network to be set up
      - name: Bench sn_node
        shell: bash
        # Criterion outputs the actual bench results to stderr "2>&1 tee output.txt" takes stderr,
        # passes to tee which displays it in the terminal and writes to output.txt
        run: cargo criterion -p sn_node --output-format bencher 2>&1 | tee -a output.txt

      - name: Build sn_node bins
        run: cd sn_node && cargo build --release --bins
        timeout-minutes: 60

      - name: Build testnet
        run: cargo build  --release --bin testnet
        timeout-minutes: 60

      - name: Start the network
        run: ./target/release/testnet --interval 30000
        id: section-startup
        env:
          RUST_LOG: "sn_node=trace"

      - name: Wait for all nodes to join
        shell: bash
        run: ./resources/scripts/wait_for_nodes_to_join.sh
        timeout-minutes: 5

        ########################
        ### Benchmark itself ###
        ########################

      - name: Bench sn_client
        shell: bash
        # Criterion outputs the actual bench results to stderr "2>&1 tee output.txt" takes stderr,
        # passes to tee which displays it in the terminal and writes to output.txt
        run: cargo criterion -p sn_client --output-format bencher 2>&1 | tee -a output.txt

      # TODO: Reenable once stable
      # - name: Bench sn_cli
      #   shell: bash
      #   # Criterion outputs the actual bench results to stderr "2>&1 tee output.txt" takes stderr,
      #   # passes to tee which displays it in the terminal and writes to output.txt
      #   run: cargo criterion -p sn_cli --output-format bencher 2>&1 | tee -a output.txt

      #################################
      ### Log any regression alerts ###
      #################################
      # Run `github-action-benchmark` action
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          # What benchmark tool the output.txt came from
          tool: 'cargo'
          # Where the output from the benchmark tool is stored
          output-file-path: output.txt
          # Where the previous data file is stored
          external-data-json-path: ./cache/benchmark-data.json
          # Workflow will fail when an alert happens
          fail-on-alert: true
          # GitHub API token to make a commit comment
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Enable alert commit comment
          comment-on-alert: true
          # 200% regression will result in alert
          alert-threshold: '200%'

      ###############
      ### Cleanup ###
      ###############
      - name: Stop the network on fail
        shell: bash
        if: failure()
        run: safe node killall || true && safe auth stop || true

      - name: Failure logs
        shell: bash
        if: failure()
        run: tail $HOME/.safe/node/local-test-network/*/*.log*
