name: Benchmarks

on:
  schedule:
    - cron:  '0 22 * * *'

env:
  CARGO_INCREMENTAL: '0'
  RUST_BACKTRACE: 1
  RUSTFLAGS: "-D warnings"

jobs:
  benchmarks:
    if: "!startsWith(github.event.pull_request.title, 'Automated version bump')"
    name: Run Benchmarks
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        id: toolchain
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: true

      - name: Build launch local network
        run: cargo build --release

      - name: Run testnet
        run: ./target/release/testnet
        if: matrix.os != 'windows-latest'
        env:
          RUST_LOG: "safe_network=trace"

      - name: Run testnet on Windows with 11 nodes
        run: ./target/release/testnet
        if: matrix.os == 'windows-latest'
        env:
          RUST_LOG: "safe_network=trace"
          NODE_COUNT: 11

      - name: Have we had a section split?
        if: matrix.os != 'windows-latest'
        run: ./resources/scripts/has_split.sh

      - name: Bench
        run: cargo bench
