name: Benchmarking

on: [pull_request, push]

env:
  # Run all cargo commands with --verbose.
  CARGO_TERM_VERBOSE: true
  RUST_BACKTRACE: 1
  SAFE_VAULT_VERSION: "0.24.0"
  # Deny all compiler warnings.
  RUSTFLAGS: "-D warnings"

jobs:
  build:
    name: Build for benchmarking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Build
        run: cargo build --release
      - name: Upload CLI
        uses: actions/upload-artifact@master
        with:
          name: safe-cli
          path: target/release/safe
      - name: Upload authd
        uses: actions/upload-artifact@master
        with:
          name: safe-authd
          path: target/release/safe-authd



  benchmark:
    name: Benchmarking ${{ matrix.benchmark }}
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        benchmark: [ keys, put ]
    steps:
      - uses: actions/checkout@v1
   
      - run: mkdir -p ~/.safe/vault
      - name: dl vault
        run: wget https://github.com/ravinderjangra/safe_vault/releases/download/${{env.SAFE_VAULT_VERSION}}/safe_vault-${{env.SAFE_VAULT_VERSION}}-x86_64-unknown-linux-musl.zip
      - run: unzip safe_vault-${{env.SAFE_VAULT_VERSION}}-x86_64-unknown-linux-musl.zip -d $HOME/.safe/vault

      - name: Setup SAFE Cli and Authd dirs
        run: |
          mkdir -p ~/.safe/cli
          mkdir -p ~/.safe/authd
        

      - name: Download CLI
        uses: actions/download-artifact@master
        with:
          name: safe-cli
          path: ./dl
    
      - name: Download authd
        uses: actions/download-artifact@master
        with:
          name: safe-authd
          path: ./dl

      - run: cp ./dl/safe $HOME/.safe/cli
      - run: cp ./dl/safe-authd $HOME/.safe/authd

      - run: ls $HOME/.safe/cli
      - run: ls $HOME/.safe/authd
      - run: echo "::add-path::$HOME/.safe/cli"
      - run: echo "::add-path::$HOME/.safe/authd"
      - run: echo $PATH
      - run: chmod +x $HOME/.safe/authd/safe-authd
      - run: chmod +x $HOME/.safe/cli/safe

      - run: chmod +x $HOME/.safe/vault/safe_vault

      

      # - name: Setup SAFE Cli and PATH etc
      #   run: |
      #     ls $HOME/.safe/cli
      #     ls $HOME/.safe/authd
      #     echo "::add-path::$HOME/.safe/cli"
      #     echo "::add-path::$HOME/.safe/authd"
      #     echo $PATH
      #     chmod +x $HOME/.safe/authd/safe-authd
      #     chmod +x $HOME/.safe/cli/safe
      #     chmod +x $HOME/.safe/vault/safe_vault

      - name: Setup The Baby
        run : safe vault run-baby-fleming -t

      - name: Benchmark 
        run: cargo bench --bench ${{ matrix.benchmark }}
        shell: bash
      
      - name: Stop the network.
        if: failure()
        run: safe vault killall || true && safe auth stop || true

      - name: Failure logs.
        if: failure()
        run: tail -f $HOME/.safe/vault/baby-fleming-vaults/*/*.log
