name: Benchmarks

on:
  schedule:
    - cron:  '0 22 * * *'

env:
  CARGO_INCREMENTAL: '0'
  RUST_BACKTRACE: 1
  RUSTFLAGS: "-D warnings"

jobs:
  benchmarks:
    if: "!startsWith(github.event.pull_request.title, 'Automated version bump')"
    name: Run Benchmarks
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        id: toolchain
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Cargo cache registry, index and build
        uses: actions/cache@v2.1.4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ steps.toolchain.outputs.rustc_hash }}-cargo-cache-${{ hashFiles('**/Cargo.lock') }}-${{ github.job }}

      - name: Build launch local network
        run: cargo build --release --features=always-joinable

      - name: Run testnet
        run: ./target/release/testnet
        if: matrix.os != 'windows-latest'
        env:
          RUST_LOG: "safe_network=trace"

      - name: Run testnet on Windows with 11 nodes
        run: ./target/release/testnet
        if: matrix.os == 'windows-latest'
        env:
          RUST_LOG: "safe_network=trace"
          NODE_COUNT: 11

      - name: Have we had a section split?
        if: matrix.os != 'windows-latest'
        run: ./scripts/has_split.sh

      - name: Bench
        run: cargo bench
