# Local Network Tests, E2E workflow.
#
# Runs client tests against latest node release

name: Local Network Tests

on: pull_request

env:
  # Run all cargo commands with --verbose.
  CARGO_TERM_VERBOSE: true
  RUST_BACKTRACE: 1
  # Deny all compiler warnings.
  RUSTFLAGS: "-D warnings"
  NODE_COUNT: "11" # this is a single section
  # I've seen 30 nodes work on CI atm.
  SAFE_AUTH_PASSPHRASE: "x"
  SAFE_AUTH_PASSWORD: "y"

jobs:
  tests:
    name: E2E tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # TODO: x-platform
        os: [ubuntu-latest]
        # os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2

      # Install Rust and required components
      - uses: actions-rs/toolchain@v1
        name: Install Rust & required components
        with:
          profile: minimal
          toolchain: stable
          override: true


      # Cache.
      - name: Cargo cache registry, index and build
        uses: actions/cache@v2.1.4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-cache-${{ hashFiles('**/Cargo.lock') }}
      
      # If we need a custom CLI version (testing out new APIs/messages etc, 
      # we'll need to supply a modified script here I suppose)
      - name: Place Safe CLI
        run:  curl -so- https://sn-api.s3.amazonaws.com/install.sh | bash
     
      - run: ~/.safe/cli/safe -V
      - run: ~/.safe/cli/safe node install

      - name: Check Node Versions
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        run : |
          echo $PATH
          ~/.safe/node/sn_node -V
      
      - run: ~/.safe/cli/safe node run-baby-fleming 

      - name: Transfer tests against local network
        shell: bash
        run: cargo test --release -- transfer

      - name: Sequence tests against local network
        shell: bash
        run: cargo test --release -- sequence
    
      - name: Map tests against local network
        shell: bash
        run: cargo test --release -- map


      # TODO: Upload all logs as artifacts....
      - name: Node Logs
        run: |
          ls $HOME/.safe/node/local-test-network
          cat $HOME/.safe/node/local-test-network/sn-node-genesis/sn_node.log
        if: failure()