name: Mini Network Tests

on: [pull_request, push]

env:
  # Run all cargo commands with --verbose.
  CARGO_TERM_VERBOSE: true
  RUST_BACKTRACE: 1
  SN_NODE_VERSION: "0.24.0"
  # Deny all compiler warnings.
  RUSTFLAGS: "-D warnings"

jobs:
  network-test:
    name: E2E against real baby
    runs-on: ubuntu-latest
    if: false
    steps:
      - uses: actions/checkout@v1
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: mkdir -p ~/.safe/node
      - name: dl node
        run: wget https://github.com/maidsafe/sn_node/releases/download/${{env.SN_NODE_VERSION}}/sn_node-${{env.SN_NODE_VERSION}}-x86_64-unknown-linux-musl.zip
      - run: unzip sn_node-${{env.SN_NODE_VERSION}}-x86_64-unknown-linux-musl.zip -d $HOME/.safe/node
      - name: Build
        run: cargo build --release
      - name: Setup Safe Cli and PATH etc
        run: |
          mkdir -p ~/.safe/cli
          mkdir -p ~/.safe/authd
          cp ./target/release/safe $HOME/.safe/cli/
          cp ./target/release/sn_authd $HOME/.safe/authd/
          ls $HOME/.safe/cli
          ls $HOME/.safe/authd
          echo "::add-path::$HOME/.safe/cli"
          echo "::add-path::$HOME/.safe/authd"
          echo $PATH
          chmod +x $HOME/.safe/authd/sn_authd
          chmod +x $HOME/.safe/cli/safe
          chmod +x $HOME/.safe/node/sn_node
      - name: Setup The Baby
        run : safe node run-baby-fleming -t
      - name: Run Tests
        run: ./resources/test-scripts/cli-tests
        shell: bash

      - name: Stop the network.
        if: failure()
        run: safe node killall || true && safe auth stop || true

      - name: Failure logs.
        if: failure()
        run: tail $HOME/.safe/node/baby-fleming-nodes/*/*.log

  network-latest-node-test:
    name: E2E against real baby with latest non-released node
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Clone sn_node
        run: git clone https://github.com/maidsafe/sn_node.git $HOME/.safe/node
      - name: Build sn_node
        run: cargo build --release --manifest-path=$HOME/.safe/node/Cargo.toml
      - run: cp $HOME/.safe/node/target/release/sn_node $HOME/.safe/node/
      - name: Build Safe CLI and sn_authd
        run: cargo build --release
      - name: Setup Safe CLI and PATH etc
        run: |
          mkdir -p ~/.safe/cli
          mkdir -p ~/.safe/authd
          cp ./target/release/safe $HOME/.safe/cli/
          cp ./target/release/sn_authd $HOME/.safe/authd/
          ls $HOME/.safe/cli
          ls $HOME/.safe/authd
          echo "::add-path::$HOME/.safe/cli"
          echo "::add-path::$HOME/.safe/authd"
          echo $PATH
          chmod +x $HOME/.safe/authd/sn_authd
          chmod +x $HOME/.safe/cli/safe
          chmod +x $HOME/.safe/node/sn_node
      - name: Setup The Baby
        run : safe node run-baby-fleming -t
      - name: Run CLI Tests
        run: ./resources/test-scripts/cli-tests
        shell: bash
      - name: Run sn_api Tests
        run: ./resources/test-scripts/api-tests
        shell: bash

      - name: Stop the network.
        if: failure()
        run: safe node killall || true && safe auth stop || true

      - name: Failure sn_node logs.
        if: failure()
        run: tail $HOME/.safe/node/baby-fleming-nodes/*/*.log

      - name: Failure sn_authd logs.
        if: failure()
        run: tail $HOME/.safe/authd/logs/sn_authd.log
