name: Mini Network Tests

on: [pull_request]

env:
  # Run all cargo commands with --verbose.
  CARGO_TERM_VERBOSE: true
  RUST_BACKTRACE: 1
  SN_NODE_VERSION: "latest"
  # Deny all compiler warnings.
  RUSTFLAGS: "-D warnings"

jobs:
  network-test:
    # if: ${{ github.repository_owner == 'maidsafe' }}
    name: E2E against real network
    runs-on: ubuntu-latest
    if: false
    steps:
      - uses: actions/checkout@v1
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: mkdir -p ~/.safe/node
      - name: dl node
        run: wget "https://sn-node.s3.eu-west-2.amazonaws.com/sn_node-${{env.SN_NODE_VERSION}}-x86_64-unknown-linux-musl.zip"
      - run: unzip sn_node-${{env.SN_NODE_VERSION}}-x86_64-unknown-linux-musl.zip -d $HOME/.safe/node
      - name: Build
        run: cargo build --release
      - name: Setup Safe Cli and PATH etc
        run: |
          mkdir -p ~/.safe/cli
          mkdir -p ~/.safe/authd
          cp ./target/release/safe $HOME/.safe/cli/
          cp ./target/release/sn_authd $HOME/.safe/authd/
          ls $HOME/.safe/cli
          ls $HOME/.safe/authd
          echo "$HOME/.safe/cli" >> $GITHUB_PATH
          echo "$HOME/.safe/authd" >> $GITHUB_PATH
          echo $PATH
          chmod +x $HOME/.safe/authd/sn_authd
          chmod +x $HOME/.safe/cli/safe
          chmod +x $HOME/.safe/node/sn_node
      - name: Setup The Network
        run : safe node run-baby-fleming -t

      - name: Run CLI Tests
        run: ./resources/test-scripts/cli-tests
        shell: bash

      - name: Run API Tests	
        run: ./resources/test-scripts/api-tests	
        shell: bash

      - name: Stop the network.
        if: failure()
        run: safe node killall || true && safe auth stop || true

      - name: Failure logs.
        if: failure()
        run: tail $HOME/.safe/node/baby-fleming-nodes/*/*.log
