# PR workflow.
#
# Runs full suite of checks, with warnings treated as errors.
# Gather code coverage stats and publish them on coveralls.io.

name: Messaging PR

on: pull_request


env:
  RUST_BACKTRACE: 1
  RUSTFLAGS: "-D warnings"

jobs:
  
  messaging-tests:
    if: "!startsWith(github.event.pull_request.title, 'Automated version bump')"
    name: Messaging Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v2
      # test for changes. (dont use baked in GHA pr/paths filter as then job wont run and we can't require itz)
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - 'src/messaging/**'
              - 'src/types/**'

      - name: Install Rust
        if: steps.changes.outputs.src == 'true'
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      # Cache.
      - name: Cargo cache registry, index and build
        if: steps.changes.outputs.src == 'true'
        uses: actions/cache@v2.1.4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-cache-${{ hashFiles('**/Cargo.lock') }}

      # Make sure tests pass.
      - name: Run cargo test
        if: steps.changes.outputs.src == 'true'
        run: cargo test --release messaging

  messaging-tests-arm:
    if: "!startsWith(github.event.pull_request.title, 'Automated version bump')"
    name: Messaging Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        target: [arm-unknown-linux-musleabi, armv7-unknown-linux-musleabihf]
    steps:
      - uses: actions/checkout@v2
      # test for changes. (dont use baked in GHA pr/paths filter as then job wont run and we can't require itz)
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - 'src/client/**'
              - 'src/messaging/**'
              - 'src/types/**'

      - uses: actions-rs/toolchain@v1
        if: steps.changes.outputs.src == 'true'
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Cargo cache registry, index and build
        if: steps.changes.outputs.src == 'true'
        uses: actions/cache@v2.1.4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-cache-${{ hashFiles('**/Cargo.lock') }}

      - name: Install cross
        run: cargo install cross

      - name: Run Doc Tests on ${{ matrix.target }} with cross
        if: steps.changes.outputs.src == 'true'
        shell: bash
        run: cross test --release messaging --target ${{ matrix.target }}
