# PR workflow.
#
# Runs full suite of checks, with warnings treated as errors.
# Gather code coverage stats and publish them on coveralls.io.

name: Url Changes


on: pull_request

env:
  RUST_BACKTRACE: 1
  RUSTFLAGS: "-D warnings"

jobs:
 
  url-tests:
    if: "!startsWith(github.event.pull_request.title, 'Automated version bump')"
    name: URL Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v2
      # test for changes. (dont use baked in GHA pr/paths filter as then job wont run and we can't require itz)
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - 'src/url/**'

              
      # Install Rust
      - uses: actions-rs/toolchain@v1
        if: steps.changes.outputs.src == 'true'
        with:
          profile: minimal
          toolchain: stable
          override: true

      # Cache.
      - name: Cargo cache registry, index and build
        if: steps.changes.outputs.src == 'true'
        uses: actions/cache@v2.1.4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-cache-${{ hashFiles('**/Cargo.lock') }}

      # Run tests.
      - shell: bash
        if: steps.changes.outputs.src == 'true'
        run: cargo test --release url 

      # Print CI machine disk space stats if the tests fail
      - name: Print CI Machine df Stats on Failure
        if: failure()
        run: df -Ph
        shell: bash

  url-tests-arm:
    if: "!startsWith(github.event.pull_request.title, 'Automated version bump')"
    name: URL Tests on ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        target: [arm-unknown-linux-musleabi, armv7-unknown-linux-musleabihf, aarch64-unknown-linux-musl]
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - 'src/url/**'
              
      - uses: actions-rs/toolchain@v1
        if: steps.changes.outputs.src == 'true'
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Cargo cache registry, index and build
        if: steps.changes.outputs.src == 'true'
        uses: actions/cache@v2.1.4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ matrix.target }}-cargo-cache-${{ hashFiles('**/Cargo.lock') }}

      - name: Install cross
        run: cargo install cross

      - shell: bash
        if: steps.changes.outputs.src == 'true'
        run: cross test --release url --target ${{ matrix.target }}

      # Print CI machine disk space stats if the tests fail
      - name: Print CI Machine df Stats on Failure
        if: failure()
        run: df -Ph
        shell: bash
