name: 'sn: PR Tests'

on: pull_request

env:
  # Turn on backtrace as needed. Generally (passing) CI should not need this.
  # RUST_BACKTRACE: 1
  # Deny all compiler warnings.
  RUSTFLAGS: "-D warnings"
  SAFE_AUTH_PASSPHRASE: "x"
  SAFE_AUTH_PASSWORD: "y"

jobs:
  tests:
    if: "!startsWith(github.event.pull_request.title, 'Automated version bump')"
    name: Run all test categories
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: messaging_changes
        with:
          filters: |
            src:
              - 'sn/src/messaging/**'
              - 'sn/src/types/**'
      - uses: dorny/paths-filter@v2
        id: node_changes
        with:
          filters: |
            src:
              - 'sn/src/node/**'
              - 'sn/src/routing/**'
              - 'sn/src/messaging/**'
              - 'sn/src/types/**'
              - 'sn/src/dbs/**'
              - 'sn/src/prefix_map/**'
              - 'sn/src/url/**'
      - uses: dorny/paths-filter@v2
        id: client_changes
        with:
          filters: |
            src:
              - 'sn/src/client/**'
              - 'sn/src/messaging/**'
              - 'sn/src/types/**'
              - 'sn/src/dbs/**'
              - 'sn/src/prefix_map/**'
              - 'sn/src/url/**'
      - uses: dorny/paths-filter@v2
        id: routing_changes
        with:
          filters: |
            src:
              - 'sn/src/routing/**'
              - 'sn/src/messaging/**'
              - 'sn/src/types/**'
              - 'sn/src/prefix_map/**'
      - uses: dorny/paths-filter@v2
        id: url_changes
        with:
          filters: |
            src:
              - 'sn/src/url/**'
      - uses: dorny/paths-filter@v2
        id: data_types_changes
        with:
          filters: |
            src:
              - 'sn/src/types/**'
      - uses: dorny/paths-filter@v2
        id: dbs_changes
        with:
          filters: |
            src:
              - 'sn/src/dbs/**'
      - uses: dorny/paths-filter@v2
        id: prefix_map_changes
        with:
          filters: |
            src:
              - 'sn/src/prefix_map/**'

      - name: Mac install ripgrep
        if: matrix.os == 'macos-latest'
        run: brew install ripgrep

      - name: ubuntu install ripgrep
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get -y install ripgrep

      - name: windows install ripgrep
        if: matrix.os == 'windows-latest'
        run: choco install ripgrep

      # Install Rust
      - name: Install Rust
        id: toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Cargo cache registry, index and build
        uses: actions/cache@v2.1.4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ steps.toolchain.outputs.rustc_hash }}-cargo-cache-${{ hashFiles('**/Cargo.lock') }}-${{ github.job }}

      - name: Build all safe_network targets
        run: cargo build --all-targets --release --features=always-joinable,test-utils

      - name: Run Data Types tests
        if: steps.data_types_changes.outputs.src == 'true'
        run: cargo test --release --features=always-joinable,test-utils -- types

      - name: Run DBs tests
        if: steps.dbs_changes.outputs.src == 'true'
        run: cargo test --release --features=always-joinable,test-utils -- dbs

      - name: Run PrefixMap tests
        if: steps.prefix_map_changes.outputs.src == 'true'
        run: cargo test --release --features=always-joinable,test-utils -- prefix_map

      - name: Run URL tests
        if: steps.url_changes.outputs.src == 'true'
        run: cargo test --release --features=always-joinable,test-utils -- url

      - name: Run Messaging tests
        if: steps.messaging_changes.outputs.src == 'true'
        run: cargo test --release --features=always-joinable,test-utils -- messaging

      - name: Run Node tests
        if: steps.node_changes.outputs.src == 'true'
        run: cargo test --release --features=always-joinable,test-utils -- node

      - name: Run Routing tests
        if: steps.routing_changes.outputs.src == 'true'
        run: cargo test --release --features=always-joinable,test-utils -- routing

      - name: Run Doc tests
        if: steps.node_changes.outputs.src == 'true'
        run: cargo test --release client --doc

      - run: ./target/release/testnet
        env:
          NODE_COUNT: 43
          RUST_LOG: safe_network=trace

      - name: Extra wait on CI for split organisation
        run: sleep 60

      - name: Was there a section split?
        run: ./scripts/has_split.sh
        id: split-check-1
        continue-on-error: true

      - name: Kill Section if no split (unix)
        if: matrix.os != 'windows-latest' && steps.split-check-1.outcome == 'failure' 
        run: |
          killall sn_node
          rm -rf ~/.safe/node
      
      - name: Kill section if no split (win)
        if: matrix.os == 'windows-latest' && steps.split-check-1.outcome == 'failure'
        shell: cmd 
        run: |
          taskkill /IM sn_node.exe /F
          rd /s /q %USERPROFILE%\.safe\node

      - name: Restart Section if no split
        if: steps.split-check-1.outcome == 'failure' 
        run: ./target/release/testnet
        env:
          NODE_COUNT: 43
          RUST_LOG: safe_network=trace

      - name: Was there a section split?
        run: ./scripts/has_split.sh
        id: split-check-2

      - name: Extra wait on CI for split organisation
        run: sleep 60

      - name: Run network asserts one by one
        shell: bash
        # FIXME: windows has an issue w/ locking of log files
        if: matrix.os != 'windows-latest'
        # here test-threads=1 is important so we dont pollute log counts by running tests in parallel
        run: timeout 5m cargo test --release --features=always-joinable,test-utils -- --ignored network_assert --test-threads=1 && sleep 5
        continue-on-error: true
        env:
          NETWORK_ASSERT_DELAY: 60
      
      # a catchall to ensure any new client api tests are run (ideally any major new section should have its own test run)
      - name: Initial client tests...
        shell: bash
        # always joinable not actually needed here, but should speed up compilation as we've just built with it
        run: cargo test --release --features=always-joinable,test-utils -- client_api --skip client_api::reg --skip client_api::blob && sleep 5
        timeout-minutes: 5

      # register api
      - name: Client reg tests against local network
        shell: bash
        run: cargo test --release --features=always-joinable,test-utils -- client_api::reg --test-threads=1 && sleep 5
        timeout-minutes: 15
        env:
          RUST_LOG: safe_network=trace,qp2p=trace
      # blob api
      - name: Client blob tests against local network
        shell: bash
        run: cargo test --release --features=always-joinable,test-utils -- client_api::blob && sleep 5
        timeout-minutes: 15
        env:
            RUST_LOG: safe_network=trace,qp2p=trace

      - name: Run example app for Blob API against local network
        timeout-minutes: 5
        shell: bash
        run: cargo run --release  --features=always-joinable,test-utils --example client_blob


      - name: Kill the current network (not needed for next test)
        if: matrix.os != 'windows-latest'
        run: |
          killall sn_node
          rm -rf ~/.safe/node
        shell: bash

      - name: Kill the current network (not needed for next test)
        if: matrix.os == 'windows-latest'
        run: |
          taskkill /IM sn_node.exe /F
          rd /s /q %USERPROFILE%\.safe\node
        shell: cmd

      # - name: Remove node dir and logs for next test
      #   if: matrix.os == 'windows-latest'
      #   run: rd /s /q %USERPROFILE%\.safe\node
      #   shell: cmd

      # - name: Remove node dir and logs for next test
      #   if: matrix.os != 'windows-latest'
      #   run: rm -rf ~/.safe/node

      # - name: Run example of split and chunk check
      #   shell: bash
      #   run: cargo run --release  --features=always-joinable,test-utils --example network_split
      #   timeout-minutes: 5

      # - name: Was there a section split?
      #   run: ./scripts/has_split.sh

      - name: Are nodes still running...?
        if: failure() && matrix.os != 'windows-latest'
        run: |
          echo "$(pgrep sn_node | wc -l) nodes still running"

      - name: Upload Node Logs
          # Upload artifacts.
        uses: actions/upload-artifact@master
        with:
          name: sn_node_logs
          path: $HOME/.safe/node/local-test-network/**
        if: failure()
