name: 'sn: PR Checks'

on: pull_request

env:
  CARGO_INCREMENTAL: '0'
  RUST_BACKTRACE: 1
  RUSTFLAGS: "-D warnings"

jobs:
  checks:
    if: "!startsWith(github.event.pull_request.title, 'Automated version bump')"
    name: Run rustfmt and clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: dorny/paths-filter@v2
        id: sn_changes
        with:
          filters: |
            src:
              - 'sn/src/**'
              - 'sn_api/src/**'
              - 'sn_cli/src/**'

      - uses: actions-rs/toolchain@v1
        if: steps.sn_changes.outputs.src == 'true'
        id: toolchain
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: true

      - name: Check formatting
        if: steps.sn_changes.outputs.src == 'true'
        run: cargo fmt --all -- --check

      - shell: bash
        if: steps.sn_changes.outputs.src == 'true'
        run: cargo clippy --all-targets --all-features

  test-publish:
    if: "!startsWith(github.event.pull_request.title, 'Automated version bump')"
    name: Test Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: dorny/paths-filter@v2
        id: sn_changes
        with:
          filters: |
            src:
              - 'sn/src/**'

      - uses: actions-rs/toolchain@v1
        if: steps.sn_changes.outputs.src == 'true'
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Publish Dry Run
        if: steps.sn_changes.outputs.src == 'true'
        run: cd sn && cargo publish --dry-run
